// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetCmCertificate
    {
        /// <summary>
        /// Get information about a Yandex Certificate Manager Certificate. For more information, see [the official documentation](https://yandex.cloud/docs/certificate-manager/concepts/).
        /// 
        /// &gt; One of `certificate_id` or `name` should be specified.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Yandex = Pulumi.Yandex;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleById = Yandex.GetCmCertificate.Invoke(new()
        ///     {
        ///         CertificateId = "certificate-id",
        ///     });
        /// 
        ///     var exampleByName = Yandex.GetCmCertificate.Invoke(new()
        ///     {
        ///         FolderId = "folder-id",
        ///         Name = "example",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetCmCertificateResult> InvokeAsync(GetCmCertificateArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCmCertificateResult>("yandex:index/getCmCertificate:getCmCertificate", args ?? new GetCmCertificateArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Certificate Manager Certificate. For more information, see [the official documentation](https://yandex.cloud/docs/certificate-manager/concepts/).
        /// 
        /// &gt; One of `certificate_id` or `name` should be specified.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Yandex = Pulumi.Yandex;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleById = Yandex.GetCmCertificate.Invoke(new()
        ///     {
        ///         CertificateId = "certificate-id",
        ///     });
        /// 
        ///     var exampleByName = Yandex.GetCmCertificate.Invoke(new()
        ///     {
        ///         FolderId = "folder-id",
        ///         Name = "example",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetCmCertificateResult> Invoke(GetCmCertificateInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCmCertificateResult>("yandex:index/getCmCertificate:getCmCertificate", args ?? new GetCmCertificateInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Certificate Manager Certificate. For more information, see [the official documentation](https://yandex.cloud/docs/certificate-manager/concepts/).
        /// 
        /// &gt; One of `certificate_id` or `name` should be specified.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Yandex = Pulumi.Yandex;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleById = Yandex.GetCmCertificate.Invoke(new()
        ///     {
        ///         CertificateId = "certificate-id",
        ///     });
        /// 
        ///     var exampleByName = Yandex.GetCmCertificate.Invoke(new()
        ///     {
        ///         FolderId = "folder-id",
        ///         Name = "example",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetCmCertificateResult> Invoke(GetCmCertificateInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCmCertificateResult>("yandex:index/getCmCertificate:getCmCertificate", args ?? new GetCmCertificateInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCmCertificateArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Certificate Id.
        /// </summary>
        [Input("certificateId")]
        public string? CertificateId { get; set; }

        /// <summary>
        /// The resource description.
        /// </summary>
        [Input("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Input("folderId")]
        public string? FolderId { get; set; }

        [Input("labels")]
        private Dictionary<string, string>? _labels;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        public Dictionary<string, string> Labels
        {
            get => _labels ?? (_labels = new Dictionary<string, string>());
            set => _labels = value;
        }

        /// <summary>
        /// The resource name.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// If `true`, the operation won't be completed while the certificate is in `VALIDATING`.
        /// </summary>
        [Input("waitValidation")]
        public bool? WaitValidation { get; set; }

        public GetCmCertificateArgs()
        {
        }
        public static new GetCmCertificateArgs Empty => new GetCmCertificateArgs();
    }

    public sealed class GetCmCertificateInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Certificate Id.
        /// </summary>
        [Input("certificateId")]
        public Input<string>? CertificateId { get; set; }

        /// <summary>
        /// The resource description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// If `true`, the operation won't be completed while the certificate is in `VALIDATING`.
        /// </summary>
        [Input("waitValidation")]
        public Input<bool>? WaitValidation { get; set; }

        public GetCmCertificateInvokeArgs()
        {
        }
        public static new GetCmCertificateInvokeArgs Empty => new GetCmCertificateInvokeArgs();
    }


    [OutputType]
    public sealed class GetCmCertificateResult
    {
        /// <summary>
        /// Certificate Id.
        /// </summary>
        public readonly string CertificateId;
        public readonly ImmutableArray<Outputs.GetCmCertificateChallengeResult> Challenges;
        /// <summary>
        /// The creation timestamp of the resource.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The `true` value means that resource is protected from accidental deletion.
        /// </summary>
        public readonly bool DeletionProtection;
        /// <summary>
        /// The resource description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Domains for this certificate. Should be specified for managed certificates.
        /// </summary>
        public readonly ImmutableArray<string> Domains;
        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Certificate issue timestamp.
        /// </summary>
        public readonly string IssuedAt;
        /// <summary>
        /// Certificate Issuer.
        /// </summary>
        public readonly string Issuer;
        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// The resource name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Certificate end valid period.
        /// </summary>
        public readonly string NotAfter;
        /// <summary>
        /// Certificate start valid period.
        /// </summary>
        public readonly string NotBefore;
        /// <summary>
        /// Certificate Serial Number.
        /// </summary>
        public readonly string Serial;
        /// <summary>
        /// Certificate status: `VALIDATING`, `INVALID`, `ISSUED`, `REVOKED`, `RENEWING` or `RENEWAL_FAILED`.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Certificate Subject.
        /// </summary>
        public readonly string Subject;
        /// <summary>
        /// Certificate type: `MANAGED` or `IMPORTED`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Certificate update timestamp.
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// If `true`, the operation won't be completed while the certificate is in `VALIDATING`.
        /// </summary>
        public readonly bool? WaitValidation;

        [OutputConstructor]
        private GetCmCertificateResult(
            string certificateId,

            ImmutableArray<Outputs.GetCmCertificateChallengeResult> challenges,

            string createdAt,

            bool deletionProtection,

            string description,

            ImmutableArray<string> domains,

            string folderId,

            string id,

            string issuedAt,

            string issuer,

            ImmutableDictionary<string, string> labels,

            string name,

            string notAfter,

            string notBefore,

            string serial,

            string status,

            string subject,

            string type,

            string updatedAt,

            bool? waitValidation)
        {
            CertificateId = certificateId;
            Challenges = challenges;
            CreatedAt = createdAt;
            DeletionProtection = deletionProtection;
            Description = description;
            Domains = domains;
            FolderId = folderId;
            Id = id;
            IssuedAt = issuedAt;
            Issuer = issuer;
            Labels = labels;
            Name = name;
            NotAfter = notAfter;
            NotBefore = notBefore;
            Serial = serial;
            Status = status;
            Subject = subject;
            Type = type;
            UpdatedAt = updatedAt;
            WaitValidation = waitValidation;
        }
    }
}
