// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetOrganizationmanagerOsLoginSettings
    {
        /// <summary>
        /// Get information about a Yandex Cloud OS Login Settings.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Yandex = Pulumi.Yandex;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myOsLoginSettingsSettings = Yandex.GetOrganizationmanagerOsLoginSettings.Invoke(new()
        ///     {
        ///         OrganizationId = "some_organization_id",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myOrganizationSshCertificatesEnabled"] = "data.yandex_organizationmanager_os_login_settings.my_os_login_settings.ssh_certificate_settings.0.enabled",
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetOrganizationmanagerOsLoginSettingsResult> InvokeAsync(GetOrganizationmanagerOsLoginSettingsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetOrganizationmanagerOsLoginSettingsResult>("yandex:index/getOrganizationmanagerOsLoginSettings:getOrganizationmanagerOsLoginSettings", args ?? new GetOrganizationmanagerOsLoginSettingsArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Cloud OS Login Settings.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Yandex = Pulumi.Yandex;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myOsLoginSettingsSettings = Yandex.GetOrganizationmanagerOsLoginSettings.Invoke(new()
        ///     {
        ///         OrganizationId = "some_organization_id",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myOrganizationSshCertificatesEnabled"] = "data.yandex_organizationmanager_os_login_settings.my_os_login_settings.ssh_certificate_settings.0.enabled",
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetOrganizationmanagerOsLoginSettingsResult> Invoke(GetOrganizationmanagerOsLoginSettingsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetOrganizationmanagerOsLoginSettingsResult>("yandex:index/getOrganizationmanagerOsLoginSettings:getOrganizationmanagerOsLoginSettings", args ?? new GetOrganizationmanagerOsLoginSettingsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Cloud OS Login Settings.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Yandex = Pulumi.Yandex;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myOsLoginSettingsSettings = Yandex.GetOrganizationmanagerOsLoginSettings.Invoke(new()
        ///     {
        ///         OrganizationId = "some_organization_id",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["myOrganizationSshCertificatesEnabled"] = "data.yandex_organizationmanager_os_login_settings.my_os_login_settings.ssh_certificate_settings.0.enabled",
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetOrganizationmanagerOsLoginSettingsResult> Invoke(GetOrganizationmanagerOsLoginSettingsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetOrganizationmanagerOsLoginSettingsResult>("yandex:index/getOrganizationmanagerOsLoginSettings:getOrganizationmanagerOsLoginSettings", args ?? new GetOrganizationmanagerOsLoginSettingsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetOrganizationmanagerOsLoginSettingsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the organization.
        /// </summary>
        [Input("organizationId")]
        public string? OrganizationId { get; set; }

        [Input("sshCertificateSettings")]
        public Inputs.GetOrganizationmanagerOsLoginSettingsSshCertificateSettingsArgs? SshCertificateSettings { get; set; }

        [Input("userSshKeySettings")]
        public Inputs.GetOrganizationmanagerOsLoginSettingsUserSshKeySettingsArgs? UserSshKeySettings { get; set; }

        public GetOrganizationmanagerOsLoginSettingsArgs()
        {
        }
        public static new GetOrganizationmanagerOsLoginSettingsArgs Empty => new GetOrganizationmanagerOsLoginSettingsArgs();
    }

    public sealed class GetOrganizationmanagerOsLoginSettingsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the organization.
        /// </summary>
        [Input("organizationId")]
        public Input<string>? OrganizationId { get; set; }

        [Input("sshCertificateSettings")]
        public Input<Inputs.GetOrganizationmanagerOsLoginSettingsSshCertificateSettingsInputArgs>? SshCertificateSettings { get; set; }

        [Input("userSshKeySettings")]
        public Input<Inputs.GetOrganizationmanagerOsLoginSettingsUserSshKeySettingsInputArgs>? UserSshKeySettings { get; set; }

        public GetOrganizationmanagerOsLoginSettingsInvokeArgs()
        {
        }
        public static new GetOrganizationmanagerOsLoginSettingsInvokeArgs Empty => new GetOrganizationmanagerOsLoginSettingsInvokeArgs();
    }


    [OutputType]
    public sealed class GetOrganizationmanagerOsLoginSettingsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// ID of the organization.
        /// </summary>
        public readonly string OrganizationId;
        public readonly Outputs.GetOrganizationmanagerOsLoginSettingsSshCertificateSettingsResult? SshCertificateSettings;
        public readonly Outputs.GetOrganizationmanagerOsLoginSettingsUserSshKeySettingsResult? UserSshKeySettings;

        [OutputConstructor]
        private GetOrganizationmanagerOsLoginSettingsResult(
            string id,

            string organizationId,

            Outputs.GetOrganizationmanagerOsLoginSettingsSshCertificateSettingsResult? sshCertificateSettings,

            Outputs.GetOrganizationmanagerOsLoginSettingsUserSshKeySettingsResult? userSshKeySettings)
        {
            Id = id;
            OrganizationId = organizationId;
            SshCertificateSettings = sshCertificateSettings;
            UserSshKeySettings = userSshKeySettings;
        }
    }
}
