// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Yandex = Pulumi.Yandex;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Auxiliary resources
    ///     var fooVpcNetwork = new Yandex.VpcNetwork("fooVpcNetwork");
    /// 
    ///     var fooVpcSubnet = new Yandex.VpcSubnet("fooVpcSubnet", new()
    ///     {
    ///         Zone = "ru-central1-a",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.5.0.0/24",
    ///         },
    ///     });
    /// 
    ///     //
    ///     // Create a new MDB Kafka Cluster.
    ///     //
    ///     var myCluster = new Yandex.MdbKafkaCluster("myCluster", new()
    ///     {
    ///         Environment = "PRESTABLE",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         SubnetIds = new[]
    ///         {
    ///             fooVpcSubnet.Id,
    ///         },
    ///         Config = new Yandex.Inputs.MdbKafkaClusterConfigArgs
    ///         {
    ///             Version = "2.8",
    ///             BrokersCount = 1,
    ///             Zones = new[]
    ///             {
    ///                 "ru-central1-a",
    ///             },
    ///             AssignPublicIp = false,
    ///             SchemaRegistry = false,
    ///             RestApi = new Yandex.Inputs.MdbKafkaClusterConfigRestApiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             KafkaUi = new Yandex.Inputs.MdbKafkaClusterConfigKafkaUiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             Kafka = new Yandex.Inputs.MdbKafkaClusterConfigKafkaArgs
    ///             {
    ///                 Resources = new Yandex.Inputs.MdbKafkaClusterConfigKafkaResourcesArgs
    ///                 {
    ///                     ResourcePresetId = "s2.micro",
    ///                     DiskTypeId = "network-ssd",
    ///                     DiskSize = 32,
    ///                 },
    ///                 KafkaConfig = new Yandex.Inputs.MdbKafkaClusterConfigKafkaKafkaConfigArgs
    ///                 {
    ///                     CompressionType = "COMPRESSION_TYPE_ZSTD",
    ///                     LogFlushIntervalMessages = "1024",
    ///                     LogFlushIntervalMs = "1000",
    ///                     LogFlushSchedulerIntervalMs = "1000",
    ///                     LogRetentionBytes = "1073741824",
    ///                     LogRetentionHours = "168",
    ///                     LogRetentionMinutes = "10080",
    ///                     LogRetentionMs = "86400000",
    ///                     LogSegmentBytes = "134217728",
    ///                     NumPartitions = "10",
    ///                     DefaultReplicationFactor = "1",
    ///                     MessageMaxBytes = "1048588",
    ///                     ReplicaFetchMaxBytes = "1048576",
    ///                     SslCipherSuites = new[]
    ///                     {
    ///                         "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
    ///                         "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    ///                     },
    ///                     OffsetsRetentionMinutes = "10080",
    ///                     SaslEnabledMechanisms = new[]
    ///                     {
    ///                         "SASL_MECHANISM_SCRAM_SHA_256",
    ///                         "SASL_MECHANISM_SCRAM_SHA_512",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///         Users = new[]
    ///         {
    ///             new Yandex.Inputs.MdbKafkaClusterUserArgs
    ///             {
    ///                 Name = "producer-application",
    ///                 Password = "password",
    ///                 Permissions = new[]
    ///                 {
    ///                     new Yandex.Inputs.MdbKafkaClusterUserPermissionArgs
    ///                     {
    ///                         TopicName = "input",
    ///                         Role = "ACCESS_ROLE_PRODUCER",
    ///                         AllowHosts = new[]
    ///                         {
    ///                             "host1.db.yandex.net",
    ///                             "host2.db.yandex.net",
    ///                         },
    ///                     },
    ///                 },
    ///             },
    ///             new Yandex.Inputs.MdbKafkaClusterUserArgs
    ///             {
    ///                 Name = "worker",
    ///                 Password = "password",
    ///                 Permissions = new[]
    ///                 {
    ///                     new Yandex.Inputs.MdbKafkaClusterUserPermissionArgs
    ///                     {
    ///                         TopicName = "input",
    ///                         Role = "ACCESS_ROLE_CONSUMER",
    ///                     },
    ///                     new Yandex.Inputs.MdbKafkaClusterUserPermissionArgs
    ///                     {
    ///                         TopicName = "output",
    ///                         Role = "ACCESS_ROLE_PRODUCER",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Yandex = Pulumi.Yandex;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Auxiliary resources
    ///     var fooVpcNetwork = new Yandex.VpcNetwork("fooVpcNetwork");
    /// 
    ///     var fooVpcSubnet = new Yandex.VpcSubnet("fooVpcSubnet", new()
    ///     {
    ///         Zone = "ru-central1-a",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.1.0.0/24",
    ///         },
    ///     });
    /// 
    ///     var bar = new Yandex.VpcSubnet("bar", new()
    ///     {
    ///         Zone = "ru-central1-b",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.2.0.0/24",
    ///         },
    ///     });
    /// 
    ///     var baz = new Yandex.VpcSubnet("baz", new()
    ///     {
    ///         Zone = "ru-central1-d",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.3.0.0/24",
    ///         },
    ///     });
    /// 
    ///     //
    ///     // Create a new MDB HA Kafka Cluster with two brokers per AZ.
    ///     // (6 brokers &amp; 3 Zookeepers)
    ///     //
    ///     var myCluster = new Yandex.MdbKafkaCluster("myCluster", new()
    ///     {
    ///         Environment = "PRESTABLE",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         SubnetIds = new[]
    ///         {
    ///             fooVpcSubnet.Id,
    ///             bar.Id,
    ///             baz.Id,
    ///         },
    ///         Config = new Yandex.Inputs.MdbKafkaClusterConfigArgs
    ///         {
    ///             Version = "2.8",
    ///             BrokersCount = 2,
    ///             Zones = new[]
    ///             {
    ///                 "ru-central1-a",
    ///                 "ru-central1-b",
    ///                 "ru-central1-d",
    ///             },
    ///             AssignPublicIp = true,
    ///             SchemaRegistry = false,
    ///             RestApi = new Yandex.Inputs.MdbKafkaClusterConfigRestApiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             KafkaUi = new Yandex.Inputs.MdbKafkaClusterConfigKafkaUiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             Kafka = new Yandex.Inputs.MdbKafkaClusterConfigKafkaArgs
    ///             {
    ///                 Resources = new Yandex.Inputs.MdbKafkaClusterConfigKafkaResourcesArgs
    ///                 {
    ///                     ResourcePresetId = "s2.medium",
    ///                     DiskTypeId = "network-ssd",
    ///                     DiskSize = 128,
    ///                 },
    ///                 KafkaConfig = new Yandex.Inputs.MdbKafkaClusterConfigKafkaKafkaConfigArgs
    ///                 {
    ///                     CompressionType = "COMPRESSION_TYPE_ZSTD",
    ///                     LogFlushIntervalMessages = "1024",
    ///                     LogFlushIntervalMs = "1000",
    ///                     LogFlushSchedulerIntervalMs = "1000",
    ///                     LogRetentionBytes = "1073741824",
    ///                     LogRetentionHours = "168",
    ///                     LogRetentionMinutes = "10080",
    ///                     LogRetentionMs = "86400000",
    ///                     LogSegmentBytes = "134217728",
    ///                     NumPartitions = "10",
    ///                     DefaultReplicationFactor = "6",
    ///                     MessageMaxBytes = "1048588",
    ///                     ReplicaFetchMaxBytes = "1048576",
    ///                     SslCipherSuites = new[]
    ///                     {
    ///                         "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
    ///                         "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    ///                     },
    ///                     OffsetsRetentionMinutes = "10080",
    ///                     SaslEnabledMechanisms = new[]
    ///                     {
    ///                         "SASL_MECHANISM_SCRAM_SHA_256",
    ///                         "SASL_MECHANISM_SCRAM_SHA_512",
    ///                     },
    ///                 },
    ///             },
    ///             Zookeeper = new Yandex.Inputs.MdbKafkaClusterConfigZookeeperArgs
    ///             {
    ///                 Resources = new Yandex.Inputs.MdbKafkaClusterConfigZookeeperResourcesArgs
    ///                 {
    ///                     ResourcePresetId = "s2.micro",
    ///                     DiskTypeId = "network-ssd",
    ///                     DiskSize = 20,
    ///                 },
    ///             },
    ///         },
    ///         Users = new[]
    ///         {
    ///             new Yandex.Inputs.MdbKafkaClusterUserArgs
    ///             {
    ///                 Name = "producer-application",
    ///                 Password = "password",
    ///                 Permissions = new[]
    ///                 {
    ///                     new Yandex.Inputs.MdbKafkaClusterUserPermissionArgs
    ///                     {
    ///                         TopicName = "input",
    ///                         Role = "ACCESS_ROLE_PRODUCER",
    ///                         AllowHosts = new[]
    ///                         {
    ///                             "host1.db.yandex.net",
    ///                             "host2.db.yandex.net",
    ///                         },
    ///                     },
    ///                 },
    ///             },
    ///             new Yandex.Inputs.MdbKafkaClusterUserArgs
    ///             {
    ///                 Name = "worker",
    ///                 Password = "password",
    ///                 Permissions = new[]
    ///                 {
    ///                     new Yandex.Inputs.MdbKafkaClusterUserPermissionArgs
    ///                     {
    ///                         TopicName = "input",
    ///                         Role = "ACCESS_ROLE_CONSUMER",
    ///                     },
    ///                     new Yandex.Inputs.MdbKafkaClusterUserPermissionArgs
    ///                     {
    ///                         TopicName = "output",
    ///                         Role = "ACCESS_ROLE_PRODUCER",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Yandex = Pulumi.Yandex;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Auxiliary resources
    ///     var fooVpcNetwork = new Yandex.VpcNetwork("fooVpcNetwork");
    /// 
    ///     var fooVpcSubnet = new Yandex.VpcSubnet("fooVpcSubnet", new()
    ///     {
    ///         Zone = "ru-central1-a",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.1.0.0/24",
    ///         },
    ///     });
    /// 
    ///     var bar = new Yandex.VpcSubnet("bar", new()
    ///     {
    ///         Zone = "ru-central1-b",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.2.0.0/24",
    ///         },
    ///     });
    /// 
    ///     var baz = new Yandex.VpcSubnet("baz", new()
    ///     {
    ///         Zone = "ru-central1-d",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.3.0.0/24",
    ///         },
    ///     });
    /// 
    ///     //
    ///     // Create a new MDB Kafka Cluster with
    ///     // KRaft-controller sub-cluster instead of Zookeeper sub-cluster.
    ///     //
    ///     var kraft_split = new Yandex.MdbKafkaCluster("kraft-split", new()
    ///     {
    ///         Environment = "PRESTABLE",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         SubnetIds = new[]
    ///         {
    ///             fooVpcSubnet.Id,
    ///             bar.Id,
    ///             baz.Id,
    ///         },
    ///         Config = new Yandex.Inputs.MdbKafkaClusterConfigArgs
    ///         {
    ///             Version = "3.6",
    ///             BrokersCount = 2,
    ///             Zones = new[]
    ///             {
    ///                 "ru-central1-a",
    ///                 "ru-central1-b",
    ///                 "ru-central1-d",
    ///             },
    ///             AssignPublicIp = true,
    ///             SchemaRegistry = false,
    ///             RestApi = new Yandex.Inputs.MdbKafkaClusterConfigRestApiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             KafkaUi = new Yandex.Inputs.MdbKafkaClusterConfigKafkaUiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             Kafka = new Yandex.Inputs.MdbKafkaClusterConfigKafkaArgs
    ///             {
    ///                 Resources = new Yandex.Inputs.MdbKafkaClusterConfigKafkaResourcesArgs
    ///                 {
    ///                     ResourcePresetId = "s2.medium",
    ///                     DiskTypeId = "network-ssd",
    ///                     DiskSize = 128,
    ///                 },
    ///                 KafkaConfig = new Yandex.Inputs.MdbKafkaClusterConfigKafkaKafkaConfigArgs
    ///                 {
    ///                     CompressionType = "COMPRESSION_TYPE_ZSTD",
    ///                     LogFlushIntervalMessages = "1024",
    ///                     LogFlushIntervalMs = "1000",
    ///                     LogFlushSchedulerIntervalMs = "1000",
    ///                     LogRetentionBytes = "1073741824",
    ///                     LogRetentionHours = "168",
    ///                     LogRetentionMinutes = "10080",
    ///                     LogRetentionMs = "86400000",
    ///                     LogSegmentBytes = "134217728",
    ///                     NumPartitions = "10",
    ///                     DefaultReplicationFactor = "6",
    ///                     MessageMaxBytes = "1048588",
    ///                     ReplicaFetchMaxBytes = "1048576",
    ///                     SslCipherSuites = new[]
    ///                     {
    ///                         "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
    ///                         "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    ///                     },
    ///                     OffsetsRetentionMinutes = "10080",
    ///                     SaslEnabledMechanisms = new[]
    ///                     {
    ///                         "SASL_MECHANISM_SCRAM_SHA_256",
    ///                         "SASL_MECHANISM_SCRAM_SHA_512",
    ///                     },
    ///                 },
    ///             },
    ///             Kraft = new Yandex.Inputs.MdbKafkaClusterConfigKraftArgs
    ///             {
    ///                 Resources = new Yandex.Inputs.MdbKafkaClusterConfigKraftResourcesArgs
    ///                 {
    ///                     ResourcePresetId = "s2.micro",
    ///                     DiskTypeId = "network-ssd",
    ///                     DiskSize = 20,
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Yandex = Pulumi.Yandex;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Auxiliary resources
    ///     var fooVpcNetwork = new Yandex.VpcNetwork("fooVpcNetwork");
    /// 
    ///     var fooVpcSubnet = new Yandex.VpcSubnet("fooVpcSubnet", new()
    ///     {
    ///         Zone = "ru-central1-a",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.1.0.0/24",
    ///         },
    ///     });
    /// 
    ///     var bar = new Yandex.VpcSubnet("bar", new()
    ///     {
    ///         Zone = "ru-central1-b",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.2.0.0/24",
    ///         },
    ///     });
    /// 
    ///     var baz = new Yandex.VpcSubnet("baz", new()
    ///     {
    ///         Zone = "ru-central1-d",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         V4CidrBlocks = new[]
    ///         {
    ///             "10.3.0.0/24",
    ///         },
    ///     });
    /// 
    ///     //
    ///     // Creating multi-host Kafka Cluster without sub-cluster of controllers, 
    ///     // using KRaft-combine quorum.
    ///     //
    ///     var kraft_combine = new Yandex.MdbKafkaCluster("kraft-combine", new()
    ///     {
    ///         Environment = "PRESTABLE",
    ///         NetworkId = fooVpcNetwork.Id,
    ///         SubnetIds = new[]
    ///         {
    ///             fooVpcSubnet.Id,
    ///             bar.Id,
    ///             baz.Id,
    ///         },
    ///         Config = new Yandex.Inputs.MdbKafkaClusterConfigArgs
    ///         {
    ///             Version = "3.6",
    ///             BrokersCount = 1,
    ///             Zones = new[]
    ///             {
    ///                 "ru-central1-a",
    ///                 "ru-central1-b",
    ///                 "ru-central1-d",
    ///             },
    ///             AssignPublicIp = true,
    ///             SchemaRegistry = false,
    ///             RestApi = new Yandex.Inputs.MdbKafkaClusterConfigRestApiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             KafkaUi = new Yandex.Inputs.MdbKafkaClusterConfigKafkaUiArgs
    ///             {
    ///                 Enabled = true,
    ///             },
    ///             Kafka = new Yandex.Inputs.MdbKafkaClusterConfigKafkaArgs
    ///             {
    ///                 Resources = new Yandex.Inputs.MdbKafkaClusterConfigKafkaResourcesArgs
    ///                 {
    ///                     ResourcePresetId = "s2.medium",
    ///                     DiskTypeId = "network-ssd",
    ///                     DiskSize = 128,
    ///                 },
    ///                 KafkaConfig = new Yandex.Inputs.MdbKafkaClusterConfigKafkaKafkaConfigArgs
    ///                 {
    ///                     CompressionType = "COMPRESSION_TYPE_ZSTD",
    ///                     LogFlushIntervalMessages = "1024",
    ///                     LogFlushIntervalMs = "1000",
    ///                     LogFlushSchedulerIntervalMs = "1000",
    ///                     LogRetentionBytes = "1073741824",
    ///                     LogRetentionHours = "168",
    ///                     LogRetentionMinutes = "10080",
    ///                     LogRetentionMs = "86400000",
    ///                     LogSegmentBytes = "134217728",
    ///                     NumPartitions = "10",
    ///                     DefaultReplicationFactor = "6",
    ///                     MessageMaxBytes = "1048588",
    ///                     ReplicaFetchMaxBytes = "1048576",
    ///                     SslCipherSuites = new[]
    ///                     {
    ///                         "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
    ///                         "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    ///                     },
    ///                     OffsetsRetentionMinutes = "10080",
    ///                     SaslEnabledMechanisms = new[]
    ///                     {
    ///                         "SASL_MECHANISM_SCRAM_SHA_256",
    ///                         "SASL_MECHANISM_SCRAM_SHA_512",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The resource can be imported by using their `resource ID`. For getting the resource ID you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or [YC CLI](https://yandex.cloud/docs/cli/quickstart).
    /// 
    /// ```sh
    /// $ pulumi import yandex:index/mdbKafkaCluster:MdbKafkaCluster &lt;resource Name&gt; &lt;resource Id&gt;
    /// ```
    /// 
    /// ```sh
    /// $ pulumi import yandex:index/mdbKafkaCluster:MdbKafkaCluster my_cluster ...
    /// ```
    /// </summary>
    [YandexResourceType("yandex:index/mdbKafkaCluster:MdbKafkaCluster")]
    public partial class MdbKafkaCluster : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Configuration of the Kafka cluster.
        /// </summary>
        [Output("config")]
        public Output<Outputs.MdbKafkaClusterConfig> Config { get; private set; } = null!;

        /// <summary>
        /// The creation timestamp of the resource.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The `true` value means that resource is protected from accidental deletion.
        /// </summary>
        [Output("deletionProtection")]
        public Output<bool> DeletionProtection { get; private set; } = null!;

        /// <summary>
        /// The resource description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Deployment environment of the Kafka cluster. Can be either `PRESTABLE` or `PRODUCTION`. The default is `PRODUCTION`.
        /// </summary>
        [Output("environment")]
        public Output<string?> Environment { get; private set; } = null!;

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        /// <summary>
        /// Aggregated health of the cluster. Can be either `ALIVE`, `DEGRADED`, `DEAD` or `HEALTH_UNKNOWN`. For more information see `health` field of JSON representation in [the official documentation](https://yandex.cloud/docs/managed-kafka/api-ref/Cluster/).
        /// </summary>
        [Output("health")]
        public Output<string> Health { get; private set; } = null!;

        /// <summary>
        /// A list of IDs of the host groups to place VMs of the cluster on.
        /// </summary>
        [Output("hostGroupIds")]
        public Output<ImmutableArray<string>> HostGroupIds { get; private set; } = null!;

        /// <summary>
        /// A host of the Kafka cluster.
        /// </summary>
        [Output("hosts")]
        public Output<ImmutableArray<Outputs.MdbKafkaClusterHost>> Hosts { get; private set; } = null!;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>> Labels { get; private set; } = null!;

        /// <summary>
        /// Maintenance policy of the Kafka cluster.
        /// </summary>
        [Output("maintenanceWindow")]
        public Output<Outputs.MdbKafkaClusterMaintenanceWindow> MaintenanceWindow { get; private set; } = null!;

        /// <summary>
        /// The resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The `VPC Network ID` of subnets which resource attached to.
        /// </summary>
        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;

        /// <summary>
        /// The list of security groups applied to resource or their components.
        /// </summary>
        [Output("securityGroupIds")]
        public Output<ImmutableArray<string>> SecurityGroupIds { get; private set; } = null!;

        /// <summary>
        /// Status of the cluster. Can be either `CREATING`, `STARTING`, `RUNNING`, `UPDATING`, `STOPPING`, `STOPPED`, `ERROR` or `STATUS_UNKNOWN`. For more information see `status` field of JSON representation in [the official documentation](https://yandex.cloud/docs/managed-kafka/api-ref/Cluster/).
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// The list of VPC subnets identifiers which resource is attached.
        /// </summary>
        [Output("subnetIds")]
        public Output<ImmutableArray<string>> SubnetIds { get; private set; } = null!;

        /// <summary>
        /// To manage topics, please switch to using a separate resource type `yandex.MdbKafkaTopic`.
        /// </summary>
        [Output("topics")]
        public Output<ImmutableArray<Outputs.MdbKafkaClusterTopic>> Topics { get; private set; } = null!;

        /// <summary>
        /// To manage users, please switch to using a separate resource type `yandex.MdbKafkaUser`.
        /// </summary>
        [Output("users")]
        public Output<ImmutableArray<Outputs.MdbKafkaClusterUser>> Users { get; private set; } = null!;


        /// <summary>
        /// Create a MdbKafkaCluster resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MdbKafkaCluster(string name, MdbKafkaClusterArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/mdbKafkaCluster:MdbKafkaCluster", name, args ?? new MdbKafkaClusterArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MdbKafkaCluster(string name, Input<string> id, MdbKafkaClusterState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/mdbKafkaCluster:MdbKafkaCluster", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MdbKafkaCluster resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MdbKafkaCluster Get(string name, Input<string> id, MdbKafkaClusterState? state = null, CustomResourceOptions? options = null)
        {
            return new MdbKafkaCluster(name, id, state, options);
        }
    }

    public sealed class MdbKafkaClusterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration of the Kafka cluster.
        /// </summary>
        [Input("config", required: true)]
        public Input<Inputs.MdbKafkaClusterConfigArgs> Config { get; set; } = null!;

        /// <summary>
        /// The `true` value means that resource is protected from accidental deletion.
        /// </summary>
        [Input("deletionProtection")]
        public Input<bool>? DeletionProtection { get; set; }

        /// <summary>
        /// The resource description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Deployment environment of the Kafka cluster. Can be either `PRESTABLE` or `PRODUCTION`. The default is `PRODUCTION`.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("hostGroupIds")]
        private InputList<string>? _hostGroupIds;

        /// <summary>
        /// A list of IDs of the host groups to place VMs of the cluster on.
        /// </summary>
        public InputList<string> HostGroupIds
        {
            get => _hostGroupIds ?? (_hostGroupIds = new InputList<string>());
            set => _hostGroupIds = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Maintenance policy of the Kafka cluster.
        /// </summary>
        [Input("maintenanceWindow")]
        public Input<Inputs.MdbKafkaClusterMaintenanceWindowArgs>? MaintenanceWindow { get; set; }

        /// <summary>
        /// The resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The `VPC Network ID` of subnets which resource attached to.
        /// </summary>
        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// The list of security groups applied to resource or their components.
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("subnetIds")]
        private InputList<string>? _subnetIds;

        /// <summary>
        /// The list of VPC subnets identifiers which resource is attached.
        /// </summary>
        public InputList<string> SubnetIds
        {
            get => _subnetIds ?? (_subnetIds = new InputList<string>());
            set => _subnetIds = value;
        }

        [Input("topics")]
        private InputList<Inputs.MdbKafkaClusterTopicArgs>? _topics;

        /// <summary>
        /// To manage topics, please switch to using a separate resource type `yandex.MdbKafkaTopic`.
        /// </summary>
        [Obsolete(@"to manage topics, please switch to using a separate resource type yandex_mdb_kafka_topic")]
        public InputList<Inputs.MdbKafkaClusterTopicArgs> Topics
        {
            get => _topics ?? (_topics = new InputList<Inputs.MdbKafkaClusterTopicArgs>());
            set => _topics = value;
        }

        [Input("users")]
        private InputList<Inputs.MdbKafkaClusterUserArgs>? _users;

        /// <summary>
        /// To manage users, please switch to using a separate resource type `yandex.MdbKafkaUser`.
        /// </summary>
        [Obsolete(@"to manage users, please switch to using a separate resource type yandex_mdb_kafka_user")]
        public InputList<Inputs.MdbKafkaClusterUserArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbKafkaClusterUserArgs>());
            set => _users = value;
        }

        public MdbKafkaClusterArgs()
        {
        }
        public static new MdbKafkaClusterArgs Empty => new MdbKafkaClusterArgs();
    }

    public sealed class MdbKafkaClusterState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration of the Kafka cluster.
        /// </summary>
        [Input("config")]
        public Input<Inputs.MdbKafkaClusterConfigGetArgs>? Config { get; set; }

        /// <summary>
        /// The creation timestamp of the resource.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The `true` value means that resource is protected from accidental deletion.
        /// </summary>
        [Input("deletionProtection")]
        public Input<bool>? DeletionProtection { get; set; }

        /// <summary>
        /// The resource description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Deployment environment of the Kafka cluster. Can be either `PRESTABLE` or `PRODUCTION`. The default is `PRODUCTION`.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        /// <summary>
        /// Aggregated health of the cluster. Can be either `ALIVE`, `DEGRADED`, `DEAD` or `HEALTH_UNKNOWN`. For more information see `health` field of JSON representation in [the official documentation](https://yandex.cloud/docs/managed-kafka/api-ref/Cluster/).
        /// </summary>
        [Input("health")]
        public Input<string>? Health { get; set; }

        [Input("hostGroupIds")]
        private InputList<string>? _hostGroupIds;

        /// <summary>
        /// A list of IDs of the host groups to place VMs of the cluster on.
        /// </summary>
        public InputList<string> HostGroupIds
        {
            get => _hostGroupIds ?? (_hostGroupIds = new InputList<string>());
            set => _hostGroupIds = value;
        }

        [Input("hosts")]
        private InputList<Inputs.MdbKafkaClusterHostGetArgs>? _hosts;

        /// <summary>
        /// A host of the Kafka cluster.
        /// </summary>
        public InputList<Inputs.MdbKafkaClusterHostGetArgs> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<Inputs.MdbKafkaClusterHostGetArgs>());
            set => _hosts = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Maintenance policy of the Kafka cluster.
        /// </summary>
        [Input("maintenanceWindow")]
        public Input<Inputs.MdbKafkaClusterMaintenanceWindowGetArgs>? MaintenanceWindow { get; set; }

        /// <summary>
        /// The resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The `VPC Network ID` of subnets which resource attached to.
        /// </summary>
        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// The list of security groups applied to resource or their components.
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        /// <summary>
        /// Status of the cluster. Can be either `CREATING`, `STARTING`, `RUNNING`, `UPDATING`, `STOPPING`, `STOPPED`, `ERROR` or `STATUS_UNKNOWN`. For more information see `status` field of JSON representation in [the official documentation](https://yandex.cloud/docs/managed-kafka/api-ref/Cluster/).
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("subnetIds")]
        private InputList<string>? _subnetIds;

        /// <summary>
        /// The list of VPC subnets identifiers which resource is attached.
        /// </summary>
        public InputList<string> SubnetIds
        {
            get => _subnetIds ?? (_subnetIds = new InputList<string>());
            set => _subnetIds = value;
        }

        [Input("topics")]
        private InputList<Inputs.MdbKafkaClusterTopicGetArgs>? _topics;

        /// <summary>
        /// To manage topics, please switch to using a separate resource type `yandex.MdbKafkaTopic`.
        /// </summary>
        [Obsolete(@"to manage topics, please switch to using a separate resource type yandex_mdb_kafka_topic")]
        public InputList<Inputs.MdbKafkaClusterTopicGetArgs> Topics
        {
            get => _topics ?? (_topics = new InputList<Inputs.MdbKafkaClusterTopicGetArgs>());
            set => _topics = value;
        }

        [Input("users")]
        private InputList<Inputs.MdbKafkaClusterUserGetArgs>? _users;

        /// <summary>
        /// To manage users, please switch to using a separate resource type `yandex.MdbKafkaUser`.
        /// </summary>
        [Obsolete(@"to manage users, please switch to using a separate resource type yandex_mdb_kafka_user")]
        public InputList<Inputs.MdbKafkaClusterUserGetArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbKafkaClusterUserGetArgs>());
            set => _users = value;
        }

        public MdbKafkaClusterState()
        {
        }
        public static new MdbKafkaClusterState Empty => new MdbKafkaClusterState();
    }
}
