// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Compute snapshot schedule. For more information, see [the official documentation](https://yandex.cloud/docs/compute/concepts/snapshot-schedule).
//
// > One of `snapshotScheduleId` or `name` should be specified.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := yandex.LookupComputeSnapshotSchedule(ctx, &yandex.LookupComputeSnapshotScheduleArgs{
//				SnapshotScheduleId: pulumi.StringRef("some_snapshot_schedule_id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupComputeSnapshotSchedule(ctx *pulumi.Context, args *LookupComputeSnapshotScheduleArgs, opts ...pulumi.InvokeOption) (*LookupComputeSnapshotScheduleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupComputeSnapshotScheduleResult
	err := ctx.Invoke("yandex:index/getComputeSnapshotSchedule:getComputeSnapshotSchedule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeSnapshotSchedule.
type LookupComputeSnapshotScheduleArgs struct {
	// The resource description.
	Description *string `pulumi:"description"`
	// IDs of the disk for snapshot schedule.
	DiskIds []string `pulumi:"diskIds"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// The resource name.
	Name *string `pulumi:"name"`
	// Time duration applied to snapshots created by this snapshot schedule. This is a signed sequence of decimal numbers, each with optional fraction and a unit suffix. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. Examples: `300ms`, `1.5h` or `2h45m`.
	RetentionPeriod  *string                                    `pulumi:"retentionPeriod"`
	SchedulePolicies []GetComputeSnapshotScheduleSchedulePolicy `pulumi:"schedulePolicies"`
	// Maximum number of snapshots for every disk of the snapshot schedule.
	SnapshotCount *int `pulumi:"snapshotCount"`
	// The ID of a specific snapshot schedule.
	SnapshotScheduleId *string `pulumi:"snapshotScheduleId"`
	// Additional attributes for snapshots created by this snapshot schedule.
	SnapshotSpecs []GetComputeSnapshotScheduleSnapshotSpec `pulumi:"snapshotSpecs"`
}

// A collection of values returned by getComputeSnapshotSchedule.
type LookupComputeSnapshotScheduleResult struct {
	// The creation timestamp of the resource.
	CreatedAt string `pulumi:"createdAt"`
	// The resource description.
	Description string `pulumi:"description"`
	// IDs of the disk for snapshot schedule.
	DiskIds []string `pulumi:"diskIds"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// The resource name.
	Name string `pulumi:"name"`
	// Time duration applied to snapshots created by this snapshot schedule. This is a signed sequence of decimal numbers, each with optional fraction and a unit suffix. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. Examples: `300ms`, `1.5h` or `2h45m`.
	RetentionPeriod  string                                     `pulumi:"retentionPeriod"`
	SchedulePolicies []GetComputeSnapshotScheduleSchedulePolicy `pulumi:"schedulePolicies"`
	// Maximum number of snapshots for every disk of the snapshot schedule.
	SnapshotCount int `pulumi:"snapshotCount"`
	// The ID of a specific snapshot schedule.
	SnapshotScheduleId string `pulumi:"snapshotScheduleId"`
	// Additional attributes for snapshots created by this snapshot schedule.
	SnapshotSpecs []GetComputeSnapshotScheduleSnapshotSpec `pulumi:"snapshotSpecs"`
	// The status of the snapshot schedule.
	Status string `pulumi:"status"`
}

func LookupComputeSnapshotScheduleOutput(ctx *pulumi.Context, args LookupComputeSnapshotScheduleOutputArgs, opts ...pulumi.InvokeOption) LookupComputeSnapshotScheduleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupComputeSnapshotScheduleResultOutput, error) {
			args := v.(LookupComputeSnapshotScheduleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getComputeSnapshotSchedule:getComputeSnapshotSchedule", args, LookupComputeSnapshotScheduleResultOutput{}, options).(LookupComputeSnapshotScheduleResultOutput), nil
		}).(LookupComputeSnapshotScheduleResultOutput)
}

// A collection of arguments for invoking getComputeSnapshotSchedule.
type LookupComputeSnapshotScheduleOutputArgs struct {
	// The resource description.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// IDs of the disk for snapshot schedule.
	DiskIds pulumi.StringArrayInput `pulumi:"diskIds"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput `pulumi:"labels"`
	// The resource name.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Time duration applied to snapshots created by this snapshot schedule. This is a signed sequence of decimal numbers, each with optional fraction and a unit suffix. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. Examples: `300ms`, `1.5h` or `2h45m`.
	RetentionPeriod  pulumi.StringPtrInput                              `pulumi:"retentionPeriod"`
	SchedulePolicies GetComputeSnapshotScheduleSchedulePolicyArrayInput `pulumi:"schedulePolicies"`
	// Maximum number of snapshots for every disk of the snapshot schedule.
	SnapshotCount pulumi.IntPtrInput `pulumi:"snapshotCount"`
	// The ID of a specific snapshot schedule.
	SnapshotScheduleId pulumi.StringPtrInput `pulumi:"snapshotScheduleId"`
	// Additional attributes for snapshots created by this snapshot schedule.
	SnapshotSpecs GetComputeSnapshotScheduleSnapshotSpecArrayInput `pulumi:"snapshotSpecs"`
}

func (LookupComputeSnapshotScheduleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeSnapshotScheduleArgs)(nil)).Elem()
}

// A collection of values returned by getComputeSnapshotSchedule.
type LookupComputeSnapshotScheduleResultOutput struct{ *pulumi.OutputState }

func (LookupComputeSnapshotScheduleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeSnapshotScheduleResult)(nil)).Elem()
}

func (o LookupComputeSnapshotScheduleResultOutput) ToLookupComputeSnapshotScheduleResultOutput() LookupComputeSnapshotScheduleResultOutput {
	return o
}

func (o LookupComputeSnapshotScheduleResultOutput) ToLookupComputeSnapshotScheduleResultOutputWithContext(ctx context.Context) LookupComputeSnapshotScheduleResultOutput {
	return o
}

// The creation timestamp of the resource.
func (o LookupComputeSnapshotScheduleResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The resource description.
func (o LookupComputeSnapshotScheduleResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.Description }).(pulumi.StringOutput)
}

// IDs of the disk for snapshot schedule.
func (o LookupComputeSnapshotScheduleResultOutput) DiskIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) []string { return v.DiskIds }).(pulumi.StringArrayOutput)
}

// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
func (o LookupComputeSnapshotScheduleResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupComputeSnapshotScheduleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o LookupComputeSnapshotScheduleResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// The resource name.
func (o LookupComputeSnapshotScheduleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.Name }).(pulumi.StringOutput)
}

// Time duration applied to snapshots created by this snapshot schedule. This is a signed sequence of decimal numbers, each with optional fraction and a unit suffix. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. Examples: `300ms`, `1.5h` or `2h45m`.
func (o LookupComputeSnapshotScheduleResultOutput) RetentionPeriod() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.RetentionPeriod }).(pulumi.StringOutput)
}

func (o LookupComputeSnapshotScheduleResultOutput) SchedulePolicies() GetComputeSnapshotScheduleSchedulePolicyArrayOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) []GetComputeSnapshotScheduleSchedulePolicy {
		return v.SchedulePolicies
	}).(GetComputeSnapshotScheduleSchedulePolicyArrayOutput)
}

// Maximum number of snapshots for every disk of the snapshot schedule.
func (o LookupComputeSnapshotScheduleResultOutput) SnapshotCount() pulumi.IntOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) int { return v.SnapshotCount }).(pulumi.IntOutput)
}

// The ID of a specific snapshot schedule.
func (o LookupComputeSnapshotScheduleResultOutput) SnapshotScheduleId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.SnapshotScheduleId }).(pulumi.StringOutput)
}

// Additional attributes for snapshots created by this snapshot schedule.
func (o LookupComputeSnapshotScheduleResultOutput) SnapshotSpecs() GetComputeSnapshotScheduleSnapshotSpecArrayOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) []GetComputeSnapshotScheduleSnapshotSpec {
		return v.SnapshotSpecs
	}).(GetComputeSnapshotScheduleSnapshotSpecArrayOutput)
}

// The status of the snapshot schedule.
func (o LookupComputeSnapshotScheduleResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeSnapshotScheduleResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupComputeSnapshotScheduleResultOutput{})
}
