// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Compute Placement group. For more information, see [the official documentation](https://yandex.cloud/docs/compute/concepts/placement-groups).
//
// > One of `groupId` or `name` should be specified.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			myGroup, err := yandex.LookupComputePlacementGroup(ctx, &yandex.LookupComputePlacementGroupArgs{
//				GroupId: pulumi.StringRef("some_group_id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("placementGroupName", myGroup.Name)
//			return nil
//		})
//	}
//
// ```
func LookupComputePlacementGroup(ctx *pulumi.Context, args *LookupComputePlacementGroupArgs, opts ...pulumi.InvokeOption) (*LookupComputePlacementGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupComputePlacementGroupResult
	err := ctx.Invoke("yandex:index/getComputePlacementGroup:getComputePlacementGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputePlacementGroup.
type LookupComputePlacementGroupArgs struct {
	// The resource description.
	Description *string `pulumi:"description"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// The ID of a specific group.
	GroupId *string `pulumi:"groupId"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// The resource name.
	Name *string `pulumi:"name"`
	// Placement strategy set for group.
	PlacementStrategy map[string]string `pulumi:"placementStrategy"`
}

// A collection of values returned by getComputePlacementGroup.
type LookupComputePlacementGroupResult struct {
	// The creation timestamp of the resource.
	CreatedAt string `pulumi:"createdAt"`
	// The resource description.
	Description *string `pulumi:"description"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId string `pulumi:"folderId"`
	// The ID of a specific group.
	GroupId string `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// The resource name.
	Name *string `pulumi:"name"`
	// Placement strategy set for group.
	PlacementStrategy map[string]string `pulumi:"placementStrategy"`
}

func LookupComputePlacementGroupOutput(ctx *pulumi.Context, args LookupComputePlacementGroupOutputArgs, opts ...pulumi.InvokeOption) LookupComputePlacementGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupComputePlacementGroupResultOutput, error) {
			args := v.(LookupComputePlacementGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getComputePlacementGroup:getComputePlacementGroup", args, LookupComputePlacementGroupResultOutput{}, options).(LookupComputePlacementGroupResultOutput), nil
		}).(LookupComputePlacementGroupResultOutput)
}

// A collection of arguments for invoking getComputePlacementGroup.
type LookupComputePlacementGroupOutputArgs struct {
	// The resource description.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// The ID of a specific group.
	GroupId pulumi.StringPtrInput `pulumi:"groupId"`
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput `pulumi:"labels"`
	// The resource name.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Placement strategy set for group.
	PlacementStrategy pulumi.StringMapInput `pulumi:"placementStrategy"`
}

func (LookupComputePlacementGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputePlacementGroupArgs)(nil)).Elem()
}

// A collection of values returned by getComputePlacementGroup.
type LookupComputePlacementGroupResultOutput struct{ *pulumi.OutputState }

func (LookupComputePlacementGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputePlacementGroupResult)(nil)).Elem()
}

func (o LookupComputePlacementGroupResultOutput) ToLookupComputePlacementGroupResultOutput() LookupComputePlacementGroupResultOutput {
	return o
}

func (o LookupComputePlacementGroupResultOutput) ToLookupComputePlacementGroupResultOutputWithContext(ctx context.Context) LookupComputePlacementGroupResultOutput {
	return o
}

// The creation timestamp of the resource.
func (o LookupComputePlacementGroupResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The resource description.
func (o LookupComputePlacementGroupResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
func (o LookupComputePlacementGroupResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The ID of a specific group.
func (o LookupComputePlacementGroupResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) string { return v.GroupId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupComputePlacementGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o LookupComputePlacementGroupResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// The resource name.
func (o LookupComputePlacementGroupResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Placement strategy set for group.
func (o LookupComputePlacementGroupResultOutput) PlacementStrategy() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputePlacementGroupResult) map[string]string { return v.PlacementStrategy }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupComputePlacementGroupResultOutput{})
}
