// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get cloud details. For more information, see [the official documentation](https://yandex.cloud/docs/resource-manager/concepts/resources-hierarchy#cloud).
//
// > Either `cloudId` or `name` must be specified.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			myCloud, err := yandex.GetResourcemanagerCloud(ctx, &yandex.GetResourcemanagerCloudArgs{
//				Name: pulumi.StringRef("foo-cloud"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("cloudCreateTimestamp", myCloud.CreatedAt)
//			return nil
//		})
//	}
//
// ```
func GetResourcemanagerCloud(ctx *pulumi.Context, args *GetResourcemanagerCloudArgs, opts ...pulumi.InvokeOption) (*GetResourcemanagerCloudResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetResourcemanagerCloudResult
	err := ctx.Invoke("yandex:index/getResourcemanagerCloud:getResourcemanagerCloud", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getResourcemanagerCloud.
type GetResourcemanagerCloudArgs struct {
	// ID of the cloud.
	CloudId *string `pulumi:"cloudId"`
	// The resource description.
	Description *string `pulumi:"description"`
	// The resource name.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getResourcemanagerCloud.
type GetResourcemanagerCloudResult struct {
	// ID of the cloud.
	CloudId string `pulumi:"cloudId"`
	// The creation timestamp of the resource.
	CreatedAt string `pulumi:"createdAt"`
	// The resource description.
	Description *string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The resource name.
	Name string `pulumi:"name"`
}

func GetResourcemanagerCloudOutput(ctx *pulumi.Context, args GetResourcemanagerCloudOutputArgs, opts ...pulumi.InvokeOption) GetResourcemanagerCloudResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetResourcemanagerCloudResultOutput, error) {
			args := v.(GetResourcemanagerCloudArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getResourcemanagerCloud:getResourcemanagerCloud", args, GetResourcemanagerCloudResultOutput{}, options).(GetResourcemanagerCloudResultOutput), nil
		}).(GetResourcemanagerCloudResultOutput)
}

// A collection of arguments for invoking getResourcemanagerCloud.
type GetResourcemanagerCloudOutputArgs struct {
	// ID of the cloud.
	CloudId pulumi.StringPtrInput `pulumi:"cloudId"`
	// The resource description.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The resource name.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetResourcemanagerCloudOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourcemanagerCloudArgs)(nil)).Elem()
}

// A collection of values returned by getResourcemanagerCloud.
type GetResourcemanagerCloudResultOutput struct{ *pulumi.OutputState }

func (GetResourcemanagerCloudResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourcemanagerCloudResult)(nil)).Elem()
}

func (o GetResourcemanagerCloudResultOutput) ToGetResourcemanagerCloudResultOutput() GetResourcemanagerCloudResultOutput {
	return o
}

func (o GetResourcemanagerCloudResultOutput) ToGetResourcemanagerCloudResultOutputWithContext(ctx context.Context) GetResourcemanagerCloudResultOutput {
	return o
}

// ID of the cloud.
func (o GetResourcemanagerCloudResultOutput) CloudId() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourcemanagerCloudResult) string { return v.CloudId }).(pulumi.StringOutput)
}

// The creation timestamp of the resource.
func (o GetResourcemanagerCloudResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourcemanagerCloudResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The resource description.
func (o GetResourcemanagerCloudResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetResourcemanagerCloudResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetResourcemanagerCloudResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourcemanagerCloudResult) string { return v.Id }).(pulumi.StringOutput)
}

// The resource name.
func (o GetResourcemanagerCloudResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourcemanagerCloudResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetResourcemanagerCloudResultOutput{})
}
