// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Cloud Serverless Container. This data source is used to define Yandex Cloud Container that can be used by other resources.
//
// > Either `containerId` or `name` must be specified.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := yandex.LookupServerlessContainer(ctx, &yandex.LookupServerlessContainerArgs{
//				ContainerId: pulumi.StringRef("are1samplecontainer11"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupServerlessContainer(ctx *pulumi.Context, args *LookupServerlessContainerArgs, opts ...pulumi.InvokeOption) (*LookupServerlessContainerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupServerlessContainerResult
	err := ctx.Invoke("yandex:index/getServerlessContainer:getServerlessContainer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerlessContainer.
type LookupServerlessContainerArgs struct {
	Connectivity *GetServerlessContainerConnectivity `pulumi:"connectivity"`
	// Yandex Cloud Serverless Container ID used to define container.
	ContainerId *string `pulumi:"containerId"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId        *string                                `pulumi:"folderId"`
	MetadataOptions *GetServerlessContainerMetadataOptions `pulumi:"metadataOptions"`
	Mounts          []GetServerlessContainerMount          `pulumi:"mounts"`
	// The resource name.
	Name    *string                        `pulumi:"name"`
	Runtime *GetServerlessContainerRuntime `pulumi:"runtime"`
	Secrets []GetServerlessContainerSecret `pulumi:"secrets"`
	// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
	StorageMounts []GetServerlessContainerStorageMount `pulumi:"storageMounts"`
}

// A collection of values returned by getServerlessContainer.
type LookupServerlessContainerResult struct {
	AsyncInvocations []GetServerlessContainerAsyncInvocation `pulumi:"asyncInvocations"`
	// Concurrency of Yandex Cloud Serverless Container.
	Concurrency  int                                 `pulumi:"concurrency"`
	Connectivity *GetServerlessContainerConnectivity `pulumi:"connectivity"`
	// Yandex Cloud Serverless Container ID used to define container.
	ContainerId *string `pulumi:"containerId"`
	// Core fraction (**0...100**) of the Yandex Cloud Serverless Container.
	CoreFraction int `pulumi:"coreFraction"`
	// Cores (**1+**) of the Yandex Cloud Serverless Container.
	Cores int `pulumi:"cores"`
	// The creation timestamp of the resource.
	CreatedAt string `pulumi:"createdAt"`
	// The resource description.
	Description string `pulumi:"description"`
	// Execution timeout in seconds (**duration format**) for Yandex Cloud Serverless Container.
	ExecutionTimeout string `pulumi:"executionTimeout"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id     string                        `pulumi:"id"`
	Images []GetServerlessContainerImage `pulumi:"images"`
	// A set of key/value label pairs which assigned to resource.
	Labels     map[string]string                 `pulumi:"labels"`
	LogOptions []GetServerlessContainerLogOption `pulumi:"logOptions"`
	// Memory in megabytes (**aligned to 128 MB**).
	Memory          int                                   `pulumi:"memory"`
	MetadataOptions GetServerlessContainerMetadataOptions `pulumi:"metadataOptions"`
	Mounts          []GetServerlessContainerMount         `pulumi:"mounts"`
	// The resource name.
	Name *string `pulumi:"name"`
	// Last revision ID of the Yandex Cloud Serverless Container.
	RevisionId string                         `pulumi:"revisionId"`
	Runtime    GetServerlessContainerRuntime  `pulumi:"runtime"`
	Secrets    []GetServerlessContainerSecret `pulumi:"secrets"`
	// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) which linked to the resource.
	ServiceAccountId string `pulumi:"serviceAccountId"`
	// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
	StorageMounts []GetServerlessContainerStorageMount `pulumi:"storageMounts"`
	// Invoke URL for the Yandex Cloud Serverless Container.
	Url string `pulumi:"url"`
}

func LookupServerlessContainerOutput(ctx *pulumi.Context, args LookupServerlessContainerOutputArgs, opts ...pulumi.InvokeOption) LookupServerlessContainerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupServerlessContainerResultOutput, error) {
			args := v.(LookupServerlessContainerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getServerlessContainer:getServerlessContainer", args, LookupServerlessContainerResultOutput{}, options).(LookupServerlessContainerResultOutput), nil
		}).(LookupServerlessContainerResultOutput)
}

// A collection of arguments for invoking getServerlessContainer.
type LookupServerlessContainerOutputArgs struct {
	Connectivity GetServerlessContainerConnectivityPtrInput `pulumi:"connectivity"`
	// Yandex Cloud Serverless Container ID used to define container.
	ContainerId pulumi.StringPtrInput `pulumi:"containerId"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId        pulumi.StringPtrInput                         `pulumi:"folderId"`
	MetadataOptions GetServerlessContainerMetadataOptionsPtrInput `pulumi:"metadataOptions"`
	Mounts          GetServerlessContainerMountArrayInput         `pulumi:"mounts"`
	// The resource name.
	Name    pulumi.StringPtrInput                  `pulumi:"name"`
	Runtime GetServerlessContainerRuntimePtrInput  `pulumi:"runtime"`
	Secrets GetServerlessContainerSecretArrayInput `pulumi:"secrets"`
	// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
	StorageMounts GetServerlessContainerStorageMountArrayInput `pulumi:"storageMounts"`
}

func (LookupServerlessContainerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessContainerArgs)(nil)).Elem()
}

// A collection of values returned by getServerlessContainer.
type LookupServerlessContainerResultOutput struct{ *pulumi.OutputState }

func (LookupServerlessContainerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessContainerResult)(nil)).Elem()
}

func (o LookupServerlessContainerResultOutput) ToLookupServerlessContainerResultOutput() LookupServerlessContainerResultOutput {
	return o
}

func (o LookupServerlessContainerResultOutput) ToLookupServerlessContainerResultOutputWithContext(ctx context.Context) LookupServerlessContainerResultOutput {
	return o
}

func (o LookupServerlessContainerResultOutput) AsyncInvocations() GetServerlessContainerAsyncInvocationArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerAsyncInvocation {
		return v.AsyncInvocations
	}).(GetServerlessContainerAsyncInvocationArrayOutput)
}

// Concurrency of Yandex Cloud Serverless Container.
func (o LookupServerlessContainerResultOutput) Concurrency() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.Concurrency }).(pulumi.IntOutput)
}

func (o LookupServerlessContainerResultOutput) Connectivity() GetServerlessContainerConnectivityPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *GetServerlessContainerConnectivity { return v.Connectivity }).(GetServerlessContainerConnectivityPtrOutput)
}

// Yandex Cloud Serverless Container ID used to define container.
func (o LookupServerlessContainerResultOutput) ContainerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.ContainerId }).(pulumi.StringPtrOutput)
}

// Core fraction (**0...100**) of the Yandex Cloud Serverless Container.
func (o LookupServerlessContainerResultOutput) CoreFraction() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.CoreFraction }).(pulumi.IntOutput)
}

// Cores (**1+**) of the Yandex Cloud Serverless Container.
func (o LookupServerlessContainerResultOutput) Cores() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.Cores }).(pulumi.IntOutput)
}

// The creation timestamp of the resource.
func (o LookupServerlessContainerResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The resource description.
func (o LookupServerlessContainerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Description }).(pulumi.StringOutput)
}

// Execution timeout in seconds (**duration format**) for Yandex Cloud Serverless Container.
func (o LookupServerlessContainerResultOutput) ExecutionTimeout() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.ExecutionTimeout }).(pulumi.StringOutput)
}

// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
func (o LookupServerlessContainerResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupServerlessContainerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupServerlessContainerResultOutput) Images() GetServerlessContainerImageArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerImage { return v.Images }).(GetServerlessContainerImageArrayOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o LookupServerlessContainerResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupServerlessContainerResultOutput) LogOptions() GetServerlessContainerLogOptionArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerLogOption { return v.LogOptions }).(GetServerlessContainerLogOptionArrayOutput)
}

// Memory in megabytes (**aligned to 128 MB**).
func (o LookupServerlessContainerResultOutput) Memory() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.Memory }).(pulumi.IntOutput)
}

func (o LookupServerlessContainerResultOutput) MetadataOptions() GetServerlessContainerMetadataOptionsOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) GetServerlessContainerMetadataOptions {
		return v.MetadataOptions
	}).(GetServerlessContainerMetadataOptionsOutput)
}

func (o LookupServerlessContainerResultOutput) Mounts() GetServerlessContainerMountArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerMount { return v.Mounts }).(GetServerlessContainerMountArrayOutput)
}

// The resource name.
func (o LookupServerlessContainerResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Last revision ID of the Yandex Cloud Serverless Container.
func (o LookupServerlessContainerResultOutput) RevisionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.RevisionId }).(pulumi.StringOutput)
}

func (o LookupServerlessContainerResultOutput) Runtime() GetServerlessContainerRuntimeOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) GetServerlessContainerRuntime { return v.Runtime }).(GetServerlessContainerRuntimeOutput)
}

func (o LookupServerlessContainerResultOutput) Secrets() GetServerlessContainerSecretArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerSecret { return v.Secrets }).(GetServerlessContainerSecretArrayOutput)
}

// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) which linked to the resource.
func (o LookupServerlessContainerResultOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.ServiceAccountId }).(pulumi.StringOutput)
}

// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
func (o LookupServerlessContainerResultOutput) StorageMounts() GetServerlessContainerStorageMountArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerStorageMount { return v.StorageMounts }).(GetServerlessContainerStorageMountArrayOutput)
}

// Invoke URL for the Yandex Cloud Serverless Container.
func (o LookupServerlessContainerResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupServerlessContainerResultOutput{})
}
