// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex VPC gateway. For more information, see [Yandex Cloud VPC](https://yandex.cloud/docs/vpc/concepts).
//
// This data source is used to define [VPC Gateways](https://yandex.cloud/docs/vpc/concepts/gateways) that can be used by other resources.
//
// > One of `gatewayId` or `name` should be specified.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := yandex.LookupVpcGateway(ctx, &yandex.LookupVpcGatewayArgs{
//				GatewayId: pulumi.StringRef("my-gateway-id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupVpcGateway(ctx *pulumi.Context, args *LookupVpcGatewayArgs, opts ...pulumi.InvokeOption) (*LookupVpcGatewayResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVpcGatewayResult
	err := ctx.Invoke("yandex:index/getVpcGateway:getVpcGateway", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpcGateway.
type LookupVpcGatewayArgs struct {
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// ID of the VPC Gateway.
	GatewayId *string `pulumi:"gatewayId"`
	// The resource name.
	Name *string `pulumi:"name"`
	// Shared egress gateway configuration. Currently empty.
	SharedEgressGateway *GetVpcGatewaySharedEgressGateway `pulumi:"sharedEgressGateway"`
}

// A collection of values returned by getVpcGateway.
type LookupVpcGatewayResult struct {
	// The creation timestamp of the resource.
	CreatedAt string `pulumi:"createdAt"`
	// The resource description.
	Description string `pulumi:"description"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId string `pulumi:"folderId"`
	// ID of the VPC Gateway.
	GatewayId string `pulumi:"gatewayId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// The resource name.
	Name string `pulumi:"name"`
	// Shared egress gateway configuration. Currently empty.
	SharedEgressGateway *GetVpcGatewaySharedEgressGateway `pulumi:"sharedEgressGateway"`
}

func LookupVpcGatewayOutput(ctx *pulumi.Context, args LookupVpcGatewayOutputArgs, opts ...pulumi.InvokeOption) LookupVpcGatewayResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupVpcGatewayResultOutput, error) {
			args := v.(LookupVpcGatewayArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getVpcGateway:getVpcGateway", args, LookupVpcGatewayResultOutput{}, options).(LookupVpcGatewayResultOutput), nil
		}).(LookupVpcGatewayResultOutput)
}

// A collection of arguments for invoking getVpcGateway.
type LookupVpcGatewayOutputArgs struct {
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// ID of the VPC Gateway.
	GatewayId pulumi.StringPtrInput `pulumi:"gatewayId"`
	// The resource name.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Shared egress gateway configuration. Currently empty.
	SharedEgressGateway GetVpcGatewaySharedEgressGatewayPtrInput `pulumi:"sharedEgressGateway"`
}

func (LookupVpcGatewayOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVpcGatewayArgs)(nil)).Elem()
}

// A collection of values returned by getVpcGateway.
type LookupVpcGatewayResultOutput struct{ *pulumi.OutputState }

func (LookupVpcGatewayResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVpcGatewayResult)(nil)).Elem()
}

func (o LookupVpcGatewayResultOutput) ToLookupVpcGatewayResultOutput() LookupVpcGatewayResultOutput {
	return o
}

func (o LookupVpcGatewayResultOutput) ToLookupVpcGatewayResultOutputWithContext(ctx context.Context) LookupVpcGatewayResultOutput {
	return o
}

// The creation timestamp of the resource.
func (o LookupVpcGatewayResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The resource description.
func (o LookupVpcGatewayResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) string { return v.Description }).(pulumi.StringOutput)
}

// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
func (o LookupVpcGatewayResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// ID of the VPC Gateway.
func (o LookupVpcGatewayResultOutput) GatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) string { return v.GatewayId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupVpcGatewayResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o LookupVpcGatewayResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// The resource name.
func (o LookupVpcGatewayResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) string { return v.Name }).(pulumi.StringOutput)
}

// Shared egress gateway configuration. Currently empty.
func (o LookupVpcGatewayResultOutput) SharedEgressGateway() GetVpcGatewaySharedEgressGatewayPtrOutput {
	return o.ApplyT(func(v LookupVpcGatewayResult) *GetVpcGatewaySharedEgressGateway { return v.SharedEgressGateway }).(GetVpcGatewaySharedEgressGatewayPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVpcGatewayResultOutput{})
}
