// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Database (dedicated) cluster. For more information, see [the official documentation](https://yandex.cloud/docs/ydb/concepts/serverless_and_dedicated).
//
// > If `databaseId` is not specified `name` and `folderId` will be used to designate Yandex Database cluster.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			myDatabase, err := yandex.LookupYdbDatabaseDedicated(ctx, &yandex.LookupYdbDatabaseDedicatedArgs{
//				DatabaseId: pulumi.StringRef("some_ydb_dedicated_database_id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("ydbApiEndpoint", myDatabase.YdbApiEndpoint)
//			return nil
//		})
//	}
//
// ```
func LookupYdbDatabaseDedicated(ctx *pulumi.Context, args *LookupYdbDatabaseDedicatedArgs, opts ...pulumi.InvokeOption) (*LookupYdbDatabaseDedicatedResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupYdbDatabaseDedicatedResult
	err := ctx.Invoke("yandex:index/getYdbDatabaseDedicated:getYdbDatabaseDedicated", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getYdbDatabaseDedicated.
type LookupYdbDatabaseDedicatedArgs struct {
	// ID of the Yandex Database cluster.
	DatabaseId *string `pulumi:"databaseId"`
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// The resource name.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getYdbDatabaseDedicated.
type LookupYdbDatabaseDedicatedResult struct {
	// Whether public IP addresses should be assigned to the Yandex Database cluster.
	AssignPublicIps bool `pulumi:"assignPublicIps"`
	// The creation timestamp of the resource.
	CreatedAt string `pulumi:"createdAt"`
	// ID of the Yandex Database cluster.
	DatabaseId *string `pulumi:"databaseId"`
	// Full database path of the Yandex Database cluster. Useful for SDK configuration.
	DatabasePath string `pulumi:"databasePath"`
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection bool `pulumi:"deletionProtection"`
	// The resource description.
	Description string `pulumi:"description"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// Location ID for the Yandex Database cluster.
	LocationId string                            `pulumi:"locationId"`
	Locations  []GetYdbDatabaseDedicatedLocation `pulumi:"locations"`
	// The resource name.
	Name *string `pulumi:"name"`
	// The `VPC Network ID` of subnets which resource attached to.
	NetworkId string `pulumi:"networkId"`
	// The Yandex Database cluster preset. Available presets can be obtained via `yc ydb resource-preset list` command.
	ResourcePresetId string                               `pulumi:"resourcePresetId"`
	ScalePolicies    []GetYdbDatabaseDedicatedScalePolicy `pulumi:"scalePolicies"`
	// The list of security groups applied to resource or their components.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// Status of the Yandex Database cluster.
	Status         string                                 `pulumi:"status"`
	StorageConfigs []GetYdbDatabaseDedicatedStorageConfig `pulumi:"storageConfigs"`
	// The list of VPC subnets identifiers which resource is attached.
	SubnetIds []string `pulumi:"subnetIds"`
	// Whether TLS is enabled for the Yandex Database cluster. Useful for SDK configuration.
	TlsEnabled bool `pulumi:"tlsEnabled"`
	// API endpoint of the Yandex Database cluster. Useful for SDK configuration.
	YdbApiEndpoint string `pulumi:"ydbApiEndpoint"`
	// Full endpoint of the Yandex Database cluster.
	YdbFullEndpoint string `pulumi:"ydbFullEndpoint"`
}

func LookupYdbDatabaseDedicatedOutput(ctx *pulumi.Context, args LookupYdbDatabaseDedicatedOutputArgs, opts ...pulumi.InvokeOption) LookupYdbDatabaseDedicatedResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupYdbDatabaseDedicatedResultOutput, error) {
			args := v.(LookupYdbDatabaseDedicatedArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getYdbDatabaseDedicated:getYdbDatabaseDedicated", args, LookupYdbDatabaseDedicatedResultOutput{}, options).(LookupYdbDatabaseDedicatedResultOutput), nil
		}).(LookupYdbDatabaseDedicatedResultOutput)
}

// A collection of arguments for invoking getYdbDatabaseDedicated.
type LookupYdbDatabaseDedicatedOutputArgs struct {
	// ID of the Yandex Database cluster.
	DatabaseId pulumi.StringPtrInput `pulumi:"databaseId"`
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection pulumi.BoolPtrInput `pulumi:"deletionProtection"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// The resource name.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupYdbDatabaseDedicatedOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupYdbDatabaseDedicatedArgs)(nil)).Elem()
}

// A collection of values returned by getYdbDatabaseDedicated.
type LookupYdbDatabaseDedicatedResultOutput struct{ *pulumi.OutputState }

func (LookupYdbDatabaseDedicatedResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupYdbDatabaseDedicatedResult)(nil)).Elem()
}

func (o LookupYdbDatabaseDedicatedResultOutput) ToLookupYdbDatabaseDedicatedResultOutput() LookupYdbDatabaseDedicatedResultOutput {
	return o
}

func (o LookupYdbDatabaseDedicatedResultOutput) ToLookupYdbDatabaseDedicatedResultOutputWithContext(ctx context.Context) LookupYdbDatabaseDedicatedResultOutput {
	return o
}

// Whether public IP addresses should be assigned to the Yandex Database cluster.
func (o LookupYdbDatabaseDedicatedResultOutput) AssignPublicIps() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) bool { return v.AssignPublicIps }).(pulumi.BoolOutput)
}

// The creation timestamp of the resource.
func (o LookupYdbDatabaseDedicatedResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// ID of the Yandex Database cluster.
func (o LookupYdbDatabaseDedicatedResultOutput) DatabaseId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) *string { return v.DatabaseId }).(pulumi.StringPtrOutput)
}

// Full database path of the Yandex Database cluster. Useful for SDK configuration.
func (o LookupYdbDatabaseDedicatedResultOutput) DatabasePath() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.DatabasePath }).(pulumi.StringOutput)
}

// The `true` value means that resource is protected from accidental deletion.
func (o LookupYdbDatabaseDedicatedResultOutput) DeletionProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) bool { return v.DeletionProtection }).(pulumi.BoolOutput)
}

// The resource description.
func (o LookupYdbDatabaseDedicatedResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.Description }).(pulumi.StringOutput)
}

// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
func (o LookupYdbDatabaseDedicatedResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupYdbDatabaseDedicatedResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o LookupYdbDatabaseDedicatedResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// Location ID for the Yandex Database cluster.
func (o LookupYdbDatabaseDedicatedResultOutput) LocationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.LocationId }).(pulumi.StringOutput)
}

func (o LookupYdbDatabaseDedicatedResultOutput) Locations() GetYdbDatabaseDedicatedLocationArrayOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) []GetYdbDatabaseDedicatedLocation { return v.Locations }).(GetYdbDatabaseDedicatedLocationArrayOutput)
}

// The resource name.
func (o LookupYdbDatabaseDedicatedResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The `VPC Network ID` of subnets which resource attached to.
func (o LookupYdbDatabaseDedicatedResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

// The Yandex Database cluster preset. Available presets can be obtained via `yc ydb resource-preset list` command.
func (o LookupYdbDatabaseDedicatedResultOutput) ResourcePresetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.ResourcePresetId }).(pulumi.StringOutput)
}

func (o LookupYdbDatabaseDedicatedResultOutput) ScalePolicies() GetYdbDatabaseDedicatedScalePolicyArrayOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) []GetYdbDatabaseDedicatedScalePolicy { return v.ScalePolicies }).(GetYdbDatabaseDedicatedScalePolicyArrayOutput)
}

// The list of security groups applied to resource or their components.
func (o LookupYdbDatabaseDedicatedResultOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) []string { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

// Status of the Yandex Database cluster.
func (o LookupYdbDatabaseDedicatedResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupYdbDatabaseDedicatedResultOutput) StorageConfigs() GetYdbDatabaseDedicatedStorageConfigArrayOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) []GetYdbDatabaseDedicatedStorageConfig {
		return v.StorageConfigs
	}).(GetYdbDatabaseDedicatedStorageConfigArrayOutput)
}

// The list of VPC subnets identifiers which resource is attached.
func (o LookupYdbDatabaseDedicatedResultOutput) SubnetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) []string { return v.SubnetIds }).(pulumi.StringArrayOutput)
}

// Whether TLS is enabled for the Yandex Database cluster. Useful for SDK configuration.
func (o LookupYdbDatabaseDedicatedResultOutput) TlsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) bool { return v.TlsEnabled }).(pulumi.BoolOutput)
}

// API endpoint of the Yandex Database cluster. Useful for SDK configuration.
func (o LookupYdbDatabaseDedicatedResultOutput) YdbApiEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.YdbApiEndpoint }).(pulumi.StringOutput)
}

// Full endpoint of the Yandex Database cluster.
func (o LookupYdbDatabaseDedicatedResultOutput) YdbFullEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupYdbDatabaseDedicatedResult) string { return v.YdbFullEndpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupYdbDatabaseDedicatedResultOutput{})
}
