// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Auxiliary resources
//			fooVpcNetwork, err := yandex.NewVpcNetwork(ctx, "fooVpcNetwork", nil)
//			if err != nil {
//				return err
//			}
//			fooVpcSubnet, err := yandex.NewVpcSubnet(ctx, "fooVpcSubnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-d"),
//				NetworkId: fooVpcNetwork.ID(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.5.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new MDB PostgreSQL Cluster.
//			_, err = yandex.NewMdbPostgresqlCluster(ctx, "myCluster", &yandex.MdbPostgresqlClusterArgs{
//				Environment: pulumi.String("PRESTABLE"),
//				NetworkId:   fooVpcNetwork.ID(),
//				Config: &yandex.MdbPostgresqlClusterConfigArgs{
//					Version: pulumi.String("15"),
//					Resources: &yandex.MdbPostgresqlClusterConfigResourcesArgs{
//						ResourcePresetId: pulumi.String("s2.micro"),
//						DiskTypeId:       pulumi.String("network-ssd"),
//						DiskSize:         pulumi.Int(16),
//					},
//					PostgresqlConfig: pulumi.StringMap{
//						"max_connections":                pulumi.String("395"),
//						"enable_parallel_hash":           pulumi.String("true"),
//						"autovacuum_vacuum_scale_factor": pulumi.String("0.34"),
//						"default_transaction_isolation":  pulumi.String("TRANSACTION_ISOLATION_READ_COMMITTED"),
//						"shared_preload_libraries":       pulumi.String("SHARED_PRELOAD_LIBRARIES_AUTO_EXPLAIN,SHARED_PRELOAD_LIBRARIES_PG_HINT_PLAN"),
//					},
//				},
//				MaintenanceWindow: &yandex.MdbPostgresqlClusterMaintenanceWindowArgs{
//					Type: pulumi.String("WEEKLY"),
//					Day:  pulumi.String("SAT"),
//					Hour: pulumi.Int(12),
//				},
//				Hosts: yandex.MdbPostgresqlClusterHostArray{
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:     pulumi.String("ru-central1-d"),
//						SubnetId: fooVpcSubnet.ID(),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Auxiliary resources
//			fooVpcNetwork, err := yandex.NewVpcNetwork(ctx, "fooVpcNetwork", nil)
//			if err != nil {
//				return err
//			}
//			fooVpcSubnet, err := yandex.NewVpcSubnet(ctx, "fooVpcSubnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-b"),
//				NetworkId: fooVpcNetwork.ID(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.1.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			bar, err := yandex.NewVpcSubnet(ctx, "bar", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-d"),
//				NetworkId: fooVpcNetwork.ID(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.2.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new MDB High Availability PostgreSQL Cluster.
//			_, err = yandex.NewMdbPostgresqlCluster(ctx, "myCluster", &yandex.MdbPostgresqlClusterArgs{
//				Environment: pulumi.String("PRESTABLE"),
//				NetworkId:   fooVpcNetwork.ID(),
//				Config: &yandex.MdbPostgresqlClusterConfigArgs{
//					Version: pulumi.String("15"),
//					Resources: &yandex.MdbPostgresqlClusterConfigResourcesArgs{
//						ResourcePresetId: pulumi.String("s2.micro"),
//						DiskTypeId:       pulumi.String("network-ssd"),
//						DiskSize:         pulumi.Int(16),
//					},
//				},
//				MaintenanceWindow: &yandex.MdbPostgresqlClusterMaintenanceWindowArgs{
//					Type: pulumi.String("ANYTIME"),
//				},
//				Hosts: yandex.MdbPostgresqlClusterHostArray{
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:     pulumi.String("ru-central1-b"),
//						SubnetId: fooVpcSubnet.ID(),
//					},
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:     pulumi.String("ru-central1-d"),
//						SubnetId: bar.ID(),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Auxiliary resources
//			foo, err := yandex.NewVpcNetwork(ctx, "foo", nil)
//			if err != nil {
//				return err
//			}
//			vpcSubnet, err := yandex.NewVpcSubnet(ctx, "vpcSubnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-a"),
//				NetworkId: foo.ID(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.1.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new MDB High Availability PostgreSQL Cluster.
//			_, err = yandex.NewMdbPostgresqlCluster(ctx, "myCluster", &yandex.MdbPostgresqlClusterArgs{
//				Description: pulumi.String("test High-Availability (HA) PostgreSQL Cluster"),
//				Environment: pulumi.String("PRESTABLE"),
//				NetworkId:   foo.ID(),
//				Config: &yandex.MdbPostgresqlClusterConfigArgs{
//					Version: pulumi.String("15"),
//					Resources: &yandex.MdbPostgresqlClusterConfigResourcesArgs{
//						ResourcePresetId: pulumi.String("s2.micro"),
//						DiskSize:         pulumi.Int(10),
//						DiskTypeId:       pulumi.String("network-ssd"),
//					},
//				},
//				Hosts: yandex.MdbPostgresqlClusterHostArray{
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:     pulumi.String("ru-central1-a"),
//						Name:     pulumi.String("host_name_a"),
//						SubnetId: vpcSubnet.ID(),
//					},
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:                  pulumi.String("ru-central1-b"),
//						Name:                  pulumi.String("host_name_b"),
//						ReplicationSourceName: pulumi.String("host_name_d"),
//						SubnetId:              pulumi.String(index / vpcSubnetVpcSubnet.Id),
//					},
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:     pulumi.String("ru-central1-d"),
//						Name:     pulumi.String("host_name_d"),
//						SubnetId: pulumi.String(yandexIndex / vpcSubnetVpcSubnet.Id),
//					},
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:     pulumi.String("ru-central1-d"),
//						Name:     pulumi.String("host_name_d_2"),
//						SubnetId: pulumi.String(yandexIndex / vpcSubnetVpcSubnet.Id),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = yandex.NewVpcSubnet(ctx, "index/vpcSubnetVpcSubnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-b"),
//				NetworkId: foo.ID(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.2.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = yandex.NewVpcSubnet(ctx, "yandexIndex/vpcSubnetVpcSubnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-d"),
//				NetworkId: foo.ID(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.3.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/airoh-io/pulumi-yandex/sdk/go/yandex"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Auxiliary resources
//			fooVpcNetwork, err := yandex.NewVpcNetwork(ctx, "fooVpcNetwork", nil)
//			if err != nil {
//				return err
//			}
//			fooVpcSubnet, err := yandex.NewVpcSubnet(ctx, "fooVpcSubnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-d"),
//				NetworkId: fooVpcNetwork.ID(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.5.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new MDB PostgreSQL Single Node Cluster from backup.
//			_, err = yandex.NewMdbPostgresqlCluster(ctx, "myCluster", &yandex.MdbPostgresqlClusterArgs{
//				Environment: pulumi.String("PRESTABLE"),
//				NetworkId:   fooVpcNetwork.ID(),
//				Restore: &yandex.MdbPostgresqlClusterRestoreArgs{
//					BackupId: pulumi.String("c9q99999999999999994cm:base_000000010000005F000000B4"),
//					Time:     pulumi.String("2021-02-11T15:04:05"),
//				},
//				Config: &yandex.MdbPostgresqlClusterConfigArgs{
//					Version: pulumi.String("15"),
//					Resources: &yandex.MdbPostgresqlClusterConfigResourcesArgs{
//						ResourcePresetId: pulumi.String("s2.micro"),
//						DiskTypeId:       pulumi.String("network-ssd"),
//						DiskSize:         pulumi.Int(16),
//					},
//					PostgresqlConfig: pulumi.StringMap{
//						"max_connections":                pulumi.String("395"),
//						"enable_parallel_hash":           pulumi.String("true"),
//						"autovacuum_vacuum_scale_factor": pulumi.String("0.34"),
//						"default_transaction_isolation":  pulumi.String("TRANSACTION_ISOLATION_READ_COMMITTED"),
//						"shared_preload_libraries":       pulumi.String("SHARED_PRELOAD_LIBRARIES_AUTO_EXPLAIN,SHARED_PRELOAD_LIBRARIES_PG_HINT_PLAN"),
//					},
//				},
//				Hosts: yandex.MdbPostgresqlClusterHostArray{
//					&yandex.MdbPostgresqlClusterHostArgs{
//						Zone:     pulumi.String("ru-central1-d"),
//						SubnetId: fooVpcSubnet.ID(),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting the resource ID you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or [YC CLI](https://yandex.cloud/docs/cli/quickstart).
//
// ```sh
// $ pulumi import yandex:index/mdbPostgresqlCluster:MdbPostgresqlCluster <resource Name> <resource Id>
// ```
//
// ```sh
// $ pulumi import yandex:index/mdbPostgresqlCluster:MdbPostgresqlCluster my_cluster ...
// ```
type MdbPostgresqlCluster struct {
	pulumi.CustomResourceState

	// Configuration of the PostgreSQL cluster.
	Config MdbPostgresqlClusterConfigOutput `pulumi:"config"`
	// The creation timestamp of the resource.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// > Deprecated! To manage databases, please switch to using a separate resource type `MdbPostgresqlDatabase`.
	//
	// Deprecated: to manage databases, please switch to using a separate resource type yandex_mdb_postgresql_database
	Databases MdbPostgresqlClusterDatabaseArrayOutput `pulumi:"databases"`
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection pulumi.BoolOutput `pulumi:"deletionProtection"`
	// The resource description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// ID of the KMS key for cluster disk encryption. Restoring without an encryption key will disable encryption if any exists.
	DiskEncryptionKeyId pulumi.StringOutput `pulumi:"diskEncryptionKeyId"`
	// Deployment environment of the PostgreSQL cluster.
	Environment pulumi.StringOutput `pulumi:"environment"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringOutput `pulumi:"folderId"`
	// Aggregated health of the cluster.
	Health pulumi.StringOutput `pulumi:"health"`
	// Host Group IDs.
	HostGroupIds pulumi.StringArrayOutput `pulumi:"hostGroupIds"`
	// Deprecated field. Will be removed in future versions.
	//
	// Deprecated: It sets name of master host. It works only when `host.name` is set. This field does not guarantee that a specific host will always be the master. We do not recommend using it. This functionality will be removed in future versions. If you are absolutely certain that you need this functionality, please contact technical support.
	HostMasterName pulumi.StringOutput `pulumi:"hostMasterName"`
	// A host of the PostgreSQL cluster.
	Hosts MdbPostgresqlClusterHostArrayOutput `pulumi:"hosts"`
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Maintenance policy of the PostgreSQL cluster.
	MaintenanceWindow MdbPostgresqlClusterMaintenanceWindowOutput `pulumi:"maintenanceWindow"`
	// The resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The `VPC Network ID` of subnets which resource attached to.
	NetworkId pulumi.StringOutput `pulumi:"networkId"`
	// The cluster will be created from the specified backup.
	Restore MdbPostgresqlClusterRestorePtrOutput `pulumi:"restore"`
	// The list of security groups applied to resource or their components.
	SecurityGroupIds pulumi.StringArrayOutput `pulumi:"securityGroupIds"`
	// Status of the cluster.
	Status pulumi.StringOutput `pulumi:"status"`
	// > Deprecated! To manage users, please switch to using a separate resource type `MdbPostgresqlUser`.
	//
	// Deprecated: to manage users, please switch to using a separate resource type yandex_mdb_postgresql_user
	Users MdbPostgresqlClusterUserArrayOutput `pulumi:"users"`
}

// NewMdbPostgresqlCluster registers a new resource with the given unique name, arguments, and options.
func NewMdbPostgresqlCluster(ctx *pulumi.Context,
	name string, args *MdbPostgresqlClusterArgs, opts ...pulumi.ResourceOption) (*MdbPostgresqlCluster, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Config == nil {
		return nil, errors.New("invalid value for required argument 'Config'")
	}
	if args.Environment == nil {
		return nil, errors.New("invalid value for required argument 'Environment'")
	}
	if args.Hosts == nil {
		return nil, errors.New("invalid value for required argument 'Hosts'")
	}
	if args.NetworkId == nil {
		return nil, errors.New("invalid value for required argument 'NetworkId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MdbPostgresqlCluster
	err := ctx.RegisterResource("yandex:index/mdbPostgresqlCluster:MdbPostgresqlCluster", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMdbPostgresqlCluster gets an existing MdbPostgresqlCluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMdbPostgresqlCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MdbPostgresqlClusterState, opts ...pulumi.ResourceOption) (*MdbPostgresqlCluster, error) {
	var resource MdbPostgresqlCluster
	err := ctx.ReadResource("yandex:index/mdbPostgresqlCluster:MdbPostgresqlCluster", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MdbPostgresqlCluster resources.
type mdbPostgresqlClusterState struct {
	// Configuration of the PostgreSQL cluster.
	Config *MdbPostgresqlClusterConfig `pulumi:"config"`
	// The creation timestamp of the resource.
	CreatedAt *string `pulumi:"createdAt"`
	// > Deprecated! To manage databases, please switch to using a separate resource type `MdbPostgresqlDatabase`.
	//
	// Deprecated: to manage databases, please switch to using a separate resource type yandex_mdb_postgresql_database
	Databases []MdbPostgresqlClusterDatabase `pulumi:"databases"`
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// The resource description.
	Description *string `pulumi:"description"`
	// ID of the KMS key for cluster disk encryption. Restoring without an encryption key will disable encryption if any exists.
	DiskEncryptionKeyId *string `pulumi:"diskEncryptionKeyId"`
	// Deployment environment of the PostgreSQL cluster.
	Environment *string `pulumi:"environment"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// Aggregated health of the cluster.
	Health *string `pulumi:"health"`
	// Host Group IDs.
	HostGroupIds []string `pulumi:"hostGroupIds"`
	// Deprecated field. Will be removed in future versions.
	//
	// Deprecated: It sets name of master host. It works only when `host.name` is set. This field does not guarantee that a specific host will always be the master. We do not recommend using it. This functionality will be removed in future versions. If you are absolutely certain that you need this functionality, please contact technical support.
	HostMasterName *string `pulumi:"hostMasterName"`
	// A host of the PostgreSQL cluster.
	Hosts []MdbPostgresqlClusterHost `pulumi:"hosts"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// Maintenance policy of the PostgreSQL cluster.
	MaintenanceWindow *MdbPostgresqlClusterMaintenanceWindow `pulumi:"maintenanceWindow"`
	// The resource name.
	Name *string `pulumi:"name"`
	// The `VPC Network ID` of subnets which resource attached to.
	NetworkId *string `pulumi:"networkId"`
	// The cluster will be created from the specified backup.
	Restore *MdbPostgresqlClusterRestore `pulumi:"restore"`
	// The list of security groups applied to resource or their components.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// Status of the cluster.
	Status *string `pulumi:"status"`
	// > Deprecated! To manage users, please switch to using a separate resource type `MdbPostgresqlUser`.
	//
	// Deprecated: to manage users, please switch to using a separate resource type yandex_mdb_postgresql_user
	Users []MdbPostgresqlClusterUser `pulumi:"users"`
}

type MdbPostgresqlClusterState struct {
	// Configuration of the PostgreSQL cluster.
	Config MdbPostgresqlClusterConfigPtrInput
	// The creation timestamp of the resource.
	CreatedAt pulumi.StringPtrInput
	// > Deprecated! To manage databases, please switch to using a separate resource type `MdbPostgresqlDatabase`.
	//
	// Deprecated: to manage databases, please switch to using a separate resource type yandex_mdb_postgresql_database
	Databases MdbPostgresqlClusterDatabaseArrayInput
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection pulumi.BoolPtrInput
	// The resource description.
	Description pulumi.StringPtrInput
	// ID of the KMS key for cluster disk encryption. Restoring without an encryption key will disable encryption if any exists.
	DiskEncryptionKeyId pulumi.StringPtrInput
	// Deployment environment of the PostgreSQL cluster.
	Environment pulumi.StringPtrInput
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput
	// Aggregated health of the cluster.
	Health pulumi.StringPtrInput
	// Host Group IDs.
	HostGroupIds pulumi.StringArrayInput
	// Deprecated field. Will be removed in future versions.
	//
	// Deprecated: It sets name of master host. It works only when `host.name` is set. This field does not guarantee that a specific host will always be the master. We do not recommend using it. This functionality will be removed in future versions. If you are absolutely certain that you need this functionality, please contact technical support.
	HostMasterName pulumi.StringPtrInput
	// A host of the PostgreSQL cluster.
	Hosts MdbPostgresqlClusterHostArrayInput
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput
	// Maintenance policy of the PostgreSQL cluster.
	MaintenanceWindow MdbPostgresqlClusterMaintenanceWindowPtrInput
	// The resource name.
	Name pulumi.StringPtrInput
	// The `VPC Network ID` of subnets which resource attached to.
	NetworkId pulumi.StringPtrInput
	// The cluster will be created from the specified backup.
	Restore MdbPostgresqlClusterRestorePtrInput
	// The list of security groups applied to resource or their components.
	SecurityGroupIds pulumi.StringArrayInput
	// Status of the cluster.
	Status pulumi.StringPtrInput
	// > Deprecated! To manage users, please switch to using a separate resource type `MdbPostgresqlUser`.
	//
	// Deprecated: to manage users, please switch to using a separate resource type yandex_mdb_postgresql_user
	Users MdbPostgresqlClusterUserArrayInput
}

func (MdbPostgresqlClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*mdbPostgresqlClusterState)(nil)).Elem()
}

type mdbPostgresqlClusterArgs struct {
	// Configuration of the PostgreSQL cluster.
	Config MdbPostgresqlClusterConfig `pulumi:"config"`
	// > Deprecated! To manage databases, please switch to using a separate resource type `MdbPostgresqlDatabase`.
	//
	// Deprecated: to manage databases, please switch to using a separate resource type yandex_mdb_postgresql_database
	Databases []MdbPostgresqlClusterDatabase `pulumi:"databases"`
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// The resource description.
	Description *string `pulumi:"description"`
	// ID of the KMS key for cluster disk encryption. Restoring without an encryption key will disable encryption if any exists.
	DiskEncryptionKeyId *string `pulumi:"diskEncryptionKeyId"`
	// Deployment environment of the PostgreSQL cluster.
	Environment string `pulumi:"environment"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// Host Group IDs.
	HostGroupIds []string `pulumi:"hostGroupIds"`
	// Deprecated field. Will be removed in future versions.
	//
	// Deprecated: It sets name of master host. It works only when `host.name` is set. This field does not guarantee that a specific host will always be the master. We do not recommend using it. This functionality will be removed in future versions. If you are absolutely certain that you need this functionality, please contact technical support.
	HostMasterName *string `pulumi:"hostMasterName"`
	// A host of the PostgreSQL cluster.
	Hosts []MdbPostgresqlClusterHost `pulumi:"hosts"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// Maintenance policy of the PostgreSQL cluster.
	MaintenanceWindow *MdbPostgresqlClusterMaintenanceWindow `pulumi:"maintenanceWindow"`
	// The resource name.
	Name *string `pulumi:"name"`
	// The `VPC Network ID` of subnets which resource attached to.
	NetworkId string `pulumi:"networkId"`
	// The cluster will be created from the specified backup.
	Restore *MdbPostgresqlClusterRestore `pulumi:"restore"`
	// The list of security groups applied to resource or their components.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// > Deprecated! To manage users, please switch to using a separate resource type `MdbPostgresqlUser`.
	//
	// Deprecated: to manage users, please switch to using a separate resource type yandex_mdb_postgresql_user
	Users []MdbPostgresqlClusterUser `pulumi:"users"`
}

// The set of arguments for constructing a MdbPostgresqlCluster resource.
type MdbPostgresqlClusterArgs struct {
	// Configuration of the PostgreSQL cluster.
	Config MdbPostgresqlClusterConfigInput
	// > Deprecated! To manage databases, please switch to using a separate resource type `MdbPostgresqlDatabase`.
	//
	// Deprecated: to manage databases, please switch to using a separate resource type yandex_mdb_postgresql_database
	Databases MdbPostgresqlClusterDatabaseArrayInput
	// The `true` value means that resource is protected from accidental deletion.
	DeletionProtection pulumi.BoolPtrInput
	// The resource description.
	Description pulumi.StringPtrInput
	// ID of the KMS key for cluster disk encryption. Restoring without an encryption key will disable encryption if any exists.
	DiskEncryptionKeyId pulumi.StringPtrInput
	// Deployment environment of the PostgreSQL cluster.
	Environment pulumi.StringInput
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput
	// Host Group IDs.
	HostGroupIds pulumi.StringArrayInput
	// Deprecated field. Will be removed in future versions.
	//
	// Deprecated: It sets name of master host. It works only when `host.name` is set. This field does not guarantee that a specific host will always be the master. We do not recommend using it. This functionality will be removed in future versions. If you are absolutely certain that you need this functionality, please contact technical support.
	HostMasterName pulumi.StringPtrInput
	// A host of the PostgreSQL cluster.
	Hosts MdbPostgresqlClusterHostArrayInput
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput
	// Maintenance policy of the PostgreSQL cluster.
	MaintenanceWindow MdbPostgresqlClusterMaintenanceWindowPtrInput
	// The resource name.
	Name pulumi.StringPtrInput
	// The `VPC Network ID` of subnets which resource attached to.
	NetworkId pulumi.StringInput
	// The cluster will be created from the specified backup.
	Restore MdbPostgresqlClusterRestorePtrInput
	// The list of security groups applied to resource or their components.
	SecurityGroupIds pulumi.StringArrayInput
	// > Deprecated! To manage users, please switch to using a separate resource type `MdbPostgresqlUser`.
	//
	// Deprecated: to manage users, please switch to using a separate resource type yandex_mdb_postgresql_user
	Users MdbPostgresqlClusterUserArrayInput
}

func (MdbPostgresqlClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*mdbPostgresqlClusterArgs)(nil)).Elem()
}

type MdbPostgresqlClusterInput interface {
	pulumi.Input

	ToMdbPostgresqlClusterOutput() MdbPostgresqlClusterOutput
	ToMdbPostgresqlClusterOutputWithContext(ctx context.Context) MdbPostgresqlClusterOutput
}

func (*MdbPostgresqlCluster) ElementType() reflect.Type {
	return reflect.TypeOf((**MdbPostgresqlCluster)(nil)).Elem()
}

func (i *MdbPostgresqlCluster) ToMdbPostgresqlClusterOutput() MdbPostgresqlClusterOutput {
	return i.ToMdbPostgresqlClusterOutputWithContext(context.Background())
}

func (i *MdbPostgresqlCluster) ToMdbPostgresqlClusterOutputWithContext(ctx context.Context) MdbPostgresqlClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbPostgresqlClusterOutput)
}

// MdbPostgresqlClusterArrayInput is an input type that accepts MdbPostgresqlClusterArray and MdbPostgresqlClusterArrayOutput values.
// You can construct a concrete instance of `MdbPostgresqlClusterArrayInput` via:
//
//	MdbPostgresqlClusterArray{ MdbPostgresqlClusterArgs{...} }
type MdbPostgresqlClusterArrayInput interface {
	pulumi.Input

	ToMdbPostgresqlClusterArrayOutput() MdbPostgresqlClusterArrayOutput
	ToMdbPostgresqlClusterArrayOutputWithContext(context.Context) MdbPostgresqlClusterArrayOutput
}

type MdbPostgresqlClusterArray []MdbPostgresqlClusterInput

func (MdbPostgresqlClusterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MdbPostgresqlCluster)(nil)).Elem()
}

func (i MdbPostgresqlClusterArray) ToMdbPostgresqlClusterArrayOutput() MdbPostgresqlClusterArrayOutput {
	return i.ToMdbPostgresqlClusterArrayOutputWithContext(context.Background())
}

func (i MdbPostgresqlClusterArray) ToMdbPostgresqlClusterArrayOutputWithContext(ctx context.Context) MdbPostgresqlClusterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbPostgresqlClusterArrayOutput)
}

// MdbPostgresqlClusterMapInput is an input type that accepts MdbPostgresqlClusterMap and MdbPostgresqlClusterMapOutput values.
// You can construct a concrete instance of `MdbPostgresqlClusterMapInput` via:
//
//	MdbPostgresqlClusterMap{ "key": MdbPostgresqlClusterArgs{...} }
type MdbPostgresqlClusterMapInput interface {
	pulumi.Input

	ToMdbPostgresqlClusterMapOutput() MdbPostgresqlClusterMapOutput
	ToMdbPostgresqlClusterMapOutputWithContext(context.Context) MdbPostgresqlClusterMapOutput
}

type MdbPostgresqlClusterMap map[string]MdbPostgresqlClusterInput

func (MdbPostgresqlClusterMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MdbPostgresqlCluster)(nil)).Elem()
}

func (i MdbPostgresqlClusterMap) ToMdbPostgresqlClusterMapOutput() MdbPostgresqlClusterMapOutput {
	return i.ToMdbPostgresqlClusterMapOutputWithContext(context.Background())
}

func (i MdbPostgresqlClusterMap) ToMdbPostgresqlClusterMapOutputWithContext(ctx context.Context) MdbPostgresqlClusterMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbPostgresqlClusterMapOutput)
}

type MdbPostgresqlClusterOutput struct{ *pulumi.OutputState }

func (MdbPostgresqlClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MdbPostgresqlCluster)(nil)).Elem()
}

func (o MdbPostgresqlClusterOutput) ToMdbPostgresqlClusterOutput() MdbPostgresqlClusterOutput {
	return o
}

func (o MdbPostgresqlClusterOutput) ToMdbPostgresqlClusterOutputWithContext(ctx context.Context) MdbPostgresqlClusterOutput {
	return o
}

// Configuration of the PostgreSQL cluster.
func (o MdbPostgresqlClusterOutput) Config() MdbPostgresqlClusterConfigOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) MdbPostgresqlClusterConfigOutput { return v.Config }).(MdbPostgresqlClusterConfigOutput)
}

// The creation timestamp of the resource.
func (o MdbPostgresqlClusterOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// > Deprecated! To manage databases, please switch to using a separate resource type `MdbPostgresqlDatabase`.
//
// Deprecated: to manage databases, please switch to using a separate resource type yandex_mdb_postgresql_database
func (o MdbPostgresqlClusterOutput) Databases() MdbPostgresqlClusterDatabaseArrayOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) MdbPostgresqlClusterDatabaseArrayOutput { return v.Databases }).(MdbPostgresqlClusterDatabaseArrayOutput)
}

// The `true` value means that resource is protected from accidental deletion.
func (o MdbPostgresqlClusterOutput) DeletionProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.BoolOutput { return v.DeletionProtection }).(pulumi.BoolOutput)
}

// The resource description.
func (o MdbPostgresqlClusterOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// ID of the KMS key for cluster disk encryption. Restoring without an encryption key will disable encryption if any exists.
func (o MdbPostgresqlClusterOutput) DiskEncryptionKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.DiskEncryptionKeyId }).(pulumi.StringOutput)
}

// Deployment environment of the PostgreSQL cluster.
func (o MdbPostgresqlClusterOutput) Environment() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.Environment }).(pulumi.StringOutput)
}

// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
func (o MdbPostgresqlClusterOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

// Aggregated health of the cluster.
func (o MdbPostgresqlClusterOutput) Health() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.Health }).(pulumi.StringOutput)
}

// Host Group IDs.
func (o MdbPostgresqlClusterOutput) HostGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringArrayOutput { return v.HostGroupIds }).(pulumi.StringArrayOutput)
}

// Deprecated field. Will be removed in future versions.
//
// Deprecated: It sets name of master host. It works only when `host.name` is set. This field does not guarantee that a specific host will always be the master. We do not recommend using it. This functionality will be removed in future versions. If you are absolutely certain that you need this functionality, please contact technical support.
func (o MdbPostgresqlClusterOutput) HostMasterName() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.HostMasterName }).(pulumi.StringOutput)
}

// A host of the PostgreSQL cluster.
func (o MdbPostgresqlClusterOutput) Hosts() MdbPostgresqlClusterHostArrayOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) MdbPostgresqlClusterHostArrayOutput { return v.Hosts }).(MdbPostgresqlClusterHostArrayOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o MdbPostgresqlClusterOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Maintenance policy of the PostgreSQL cluster.
func (o MdbPostgresqlClusterOutput) MaintenanceWindow() MdbPostgresqlClusterMaintenanceWindowOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) MdbPostgresqlClusterMaintenanceWindowOutput { return v.MaintenanceWindow }).(MdbPostgresqlClusterMaintenanceWindowOutput)
}

// The resource name.
func (o MdbPostgresqlClusterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The `VPC Network ID` of subnets which resource attached to.
func (o MdbPostgresqlClusterOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.NetworkId }).(pulumi.StringOutput)
}

// The cluster will be created from the specified backup.
func (o MdbPostgresqlClusterOutput) Restore() MdbPostgresqlClusterRestorePtrOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) MdbPostgresqlClusterRestorePtrOutput { return v.Restore }).(MdbPostgresqlClusterRestorePtrOutput)
}

// The list of security groups applied to resource or their components.
func (o MdbPostgresqlClusterOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringArrayOutput { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

// Status of the cluster.
func (o MdbPostgresqlClusterOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// > Deprecated! To manage users, please switch to using a separate resource type `MdbPostgresqlUser`.
//
// Deprecated: to manage users, please switch to using a separate resource type yandex_mdb_postgresql_user
func (o MdbPostgresqlClusterOutput) Users() MdbPostgresqlClusterUserArrayOutput {
	return o.ApplyT(func(v *MdbPostgresqlCluster) MdbPostgresqlClusterUserArrayOutput { return v.Users }).(MdbPostgresqlClusterUserArrayOutput)
}

type MdbPostgresqlClusterArrayOutput struct{ *pulumi.OutputState }

func (MdbPostgresqlClusterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MdbPostgresqlCluster)(nil)).Elem()
}

func (o MdbPostgresqlClusterArrayOutput) ToMdbPostgresqlClusterArrayOutput() MdbPostgresqlClusterArrayOutput {
	return o
}

func (o MdbPostgresqlClusterArrayOutput) ToMdbPostgresqlClusterArrayOutputWithContext(ctx context.Context) MdbPostgresqlClusterArrayOutput {
	return o
}

func (o MdbPostgresqlClusterArrayOutput) Index(i pulumi.IntInput) MdbPostgresqlClusterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MdbPostgresqlCluster {
		return vs[0].([]*MdbPostgresqlCluster)[vs[1].(int)]
	}).(MdbPostgresqlClusterOutput)
}

type MdbPostgresqlClusterMapOutput struct{ *pulumi.OutputState }

func (MdbPostgresqlClusterMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MdbPostgresqlCluster)(nil)).Elem()
}

func (o MdbPostgresqlClusterMapOutput) ToMdbPostgresqlClusterMapOutput() MdbPostgresqlClusterMapOutput {
	return o
}

func (o MdbPostgresqlClusterMapOutput) ToMdbPostgresqlClusterMapOutputWithContext(ctx context.Context) MdbPostgresqlClusterMapOutput {
	return o
}

func (o MdbPostgresqlClusterMapOutput) MapIndex(k pulumi.StringInput) MdbPostgresqlClusterOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MdbPostgresqlCluster {
		return vs[0].(map[string]*MdbPostgresqlCluster)[vs[1].(string)]
	}).(MdbPostgresqlClusterOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MdbPostgresqlClusterInput)(nil)).Elem(), &MdbPostgresqlCluster{})
	pulumi.RegisterInputType(reflect.TypeOf((*MdbPostgresqlClusterArrayInput)(nil)).Elem(), MdbPostgresqlClusterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MdbPostgresqlClusterMapInput)(nil)).Elem(), MdbPostgresqlClusterMap{})
	pulumi.RegisterOutputType(MdbPostgresqlClusterOutput{})
	pulumi.RegisterOutputType(MdbPostgresqlClusterArrayOutput{})
	pulumi.RegisterOutputType(MdbPostgresqlClusterMapOutput{})
}
