// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseShard
    {
        public readonly ImmutableArray<string> Hosts;
        public readonly string? Name;

        [OutputConstructor]
        private DatatransferEndpointSettingsClickhouseSourceConnectionConnectionOptionsOnPremiseShard(
            ImmutableArray<string> hosts,

            string? name)
        {
            Hosts = hosts;
            Name = name;
        }
    }
}
