// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetFunctionAsyncInvocationResult
    {
        /// <summary>
        /// Maximum number of retries for async invocation.
        /// </summary>
        public readonly int RetriesCount;
        /// <summary>
        /// Service account used for async invocation.
        /// </summary>
        public readonly string ServiceAccountId;
        /// <summary>
        /// Target for unsuccessful async invocation.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFunctionAsyncInvocationYmqFailureTargetResult> YmqFailureTargets;
        /// <summary>
        /// Target for successful async invocation.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFunctionAsyncInvocationYmqSuccessTargetResult> YmqSuccessTargets;

        [OutputConstructor]
        private GetFunctionAsyncInvocationResult(
            int retriesCount,

            string serviceAccountId,

            ImmutableArray<Outputs.GetFunctionAsyncInvocationYmqFailureTargetResult> ymqFailureTargets,

            ImmutableArray<Outputs.GetFunctionAsyncInvocationYmqSuccessTargetResult> ymqSuccessTargets)
        {
            RetriesCount = retriesCount;
            ServiceAccountId = serviceAccountId;
            YmqFailureTargets = ymqFailureTargets;
            YmqSuccessTargets = ymqSuccessTargets;
        }
    }
}
