// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetSwsWafProfileRuleSetYaRuleSetRuleSetResult
    {
        /// <summary>
        /// Name of the rule set.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Type of the rule set.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Version of the rule set.
        /// </summary>
        public readonly string Version;
        public readonly string WafProfileId;

        [OutputConstructor]
        private GetSwsWafProfileRuleSetYaRuleSetRuleSetResult(
            string name,

            string type,

            string version,

            string wafProfileId)
        {
            Name = name;
            Type = type;
            Version = version;
            WafProfileId = wafProfileId;
        }
    }
}
