// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetApiGatewayCanaryArgs : global::Pulumi.InvokeArgs
    {
        [Input("variables")]
        private Dictionary<string, string>? _variables;

        /// <summary>
        /// A list of values for variables in gateway specification of canary release.
        /// </summary>
        public Dictionary<string, string> Variables
        {
            get => _variables ?? (_variables = new Dictionary<string, string>());
            set => _variables = value;
        }

        /// <summary>
        /// Percentage of requests, which will be processed by canary release.
        /// </summary>
        [Input("weight")]
        public int? Weight { get; set; }

        public GetApiGatewayCanaryArgs()
        {
        }
        public static new GetApiGatewayCanaryArgs Empty => new GetApiGatewayCanaryArgs();
    }
}
