// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbGreenplumClusterBackgroundActivityArgs : global::Pulumi.InvokeArgs
    {
        [Input("analyzeAndVacuums", required: true)]
        private List<Inputs.GetMdbGreenplumClusterBackgroundActivityAnalyzeAndVacuumArgs>? _analyzeAndVacuums;

        /// <summary>
        /// Block to configure 'ANALYZE' and 'VACUUM' daily operations.
        /// </summary>
        public List<Inputs.GetMdbGreenplumClusterBackgroundActivityAnalyzeAndVacuumArgs> AnalyzeAndVacuums
        {
            get => _analyzeAndVacuums ?? (_analyzeAndVacuums = new List<Inputs.GetMdbGreenplumClusterBackgroundActivityAnalyzeAndVacuumArgs>());
            set => _analyzeAndVacuums = value;
        }

        [Input("queryKillerIdleInTransactions", required: true)]
        private List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleInTransactionArgs>? _queryKillerIdleInTransactions;

        /// <summary>
        /// Block to configure script that kills long running queries that are in `idle in transaction` state.
        /// </summary>
        public List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleInTransactionArgs> QueryKillerIdleInTransactions
        {
            get => _queryKillerIdleInTransactions ?? (_queryKillerIdleInTransactions = new List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleInTransactionArgs>());
            set => _queryKillerIdleInTransactions = value;
        }

        [Input("queryKillerIdles", required: true)]
        private List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleArgs>? _queryKillerIdles;

        /// <summary>
        /// Block to configure script that kills long running queries that are in `idle` state.
        /// </summary>
        public List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleArgs> QueryKillerIdles
        {
            get => _queryKillerIdles ?? (_queryKillerIdles = new List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleArgs>());
            set => _queryKillerIdles = value;
        }

        [Input("queryKillerLongRunnings", required: true)]
        private List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerLongRunningArgs>? _queryKillerLongRunnings;

        /// <summary>
        /// Block to configure script that kills long running queries (in any state).
        /// </summary>
        public List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerLongRunningArgs> QueryKillerLongRunnings
        {
            get => _queryKillerLongRunnings ?? (_queryKillerLongRunnings = new List<Inputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerLongRunningArgs>());
            set => _queryKillerLongRunnings = value;
        }

        public GetMdbGreenplumClusterBackgroundActivityArgs()
        {
        }
        public static new GetMdbGreenplumClusterBackgroundActivityArgs Empty => new GetMdbGreenplumClusterBackgroundActivityArgs();
    }
}
