// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbPostgresqlDatabaseExtensionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the database extension. For more information on available extensions see [the official documentation](https://yandex.cloud/docs/managed-postgresql/operations/cluster-extensions). Name of the database extension. For more information on available extensions see [the official documentation](https://yandex.cloud/docs/managed-postgresql/operations/cluster-extensions).
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetMdbPostgresqlDatabaseExtensionArgs()
        {
        }
        public static new GetMdbPostgresqlDatabaseExtensionArgs Empty => new GetMdbPostgresqlDatabaseExtensionArgs();
    }
}
