// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetServerlessContainerMountInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// One of the available mount types. Disk available during the function execution time.
        /// </summary>
        [Input("ephemeralDisk")]
        public Input<Inputs.GetServerlessContainerMountEphemeralDiskInputArgs>? EphemeralDisk { get; set; }

        /// <summary>
        /// Mount’s accessibility mode. Valid values are `ro` and `rw`.
        /// </summary>
        [Input("mode", required: true)]
        public Input<string> Mode { get; set; } = null!;

        /// <summary>
        /// Path inside the container to access the directory in which the target is mounted.
        /// </summary>
        [Input("mountPointPath", required: true)]
        public Input<string> MountPointPath { get; set; } = null!;

        /// <summary>
        /// Available mount types. Object storage as a mount.
        /// </summary>
        [Input("objectStorage")]
        public Input<Inputs.GetServerlessContainerMountObjectStorageInputArgs>? ObjectStorage { get; set; }

        public GetServerlessContainerMountInputArgs()
        {
        }
        public static new GetServerlessContainerMountInputArgs Empty => new GetServerlessContainerMountInputArgs();
    }
}
