name: Cleanup Old Artifacts

on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    name: Delete Old Workflow Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 30 days
        uses: actions/github-script@v7
        with:
          script: |
            const days_to_keep = 30;
            const cutoff = new Date();
            cutoff.setDate(cutoff.getDate() - days_to_keep);
            
            const artifacts = await github.paginate(github.rest.actions.listArtifactsForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            
            for (const artifact of artifacts) {
              const created = new Date(artifact.created_at);
              if (created < cutoff) {
                console.log(`Deleting artifact: ${artifact.name} (created: ${artifact.created_at})`);
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id
                });
              }
            }
