name: Update Dependencies

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-terraform-provider:
    name: Check for Terraform Provider Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Latest Terraform Provider Version
        id: check
        run: |
          CURRENT=$(grep 'terraform-provider-yandex' provider/go.mod | awk '{print $2}')
          LATEST=$(curl -s https://api.github.com/repos/yandex-cloud/terraform-provider-yandex/releases/latest | jq -r .tag_name)
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo "latest=$LATEST" >> $GITHUB_OUTPUT
          echo "Current: $CURRENT, Latest: $LATEST"

      - name: Create Issue if Update Available
        if: steps.check.outputs.current != steps.check.outputs.latest
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Terraform Yandex Provider Available: ${{ steps.check.outputs.latest }}',
              body: `A new version of terraform-provider-yandex is available!
              
              **Current Version:** ${{ steps.check.outputs.current }}
              **Latest Version:** ${{ steps.check.outputs.latest }}
              
              To update:
              1. Update \`provider/go.mod\` with the new version
              2. Run \`cd provider && go mod tidy\`
              3. Regenerate SDKs with \`make build_sdks\`
              4. Test and create a PR
              
              See [PUBLISHING_NPM.md](./PUBLISHING_NPM.md) for details.`,
              labels: ['dependencies', 'terraform-provider']
            })

  check-pulumi-bridge:
    name: Check for Pulumi Bridge Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Latest Bridge Version
        id: check
        run: |
          CURRENT=$(grep 'pulumi-terraform-bridge' provider/go.mod | awk '{print $2}')
          LATEST=$(curl -s https://api.github.com/repos/pulumi/pulumi-terraform-bridge/releases | jq -r '.[0].tag_name')
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Create Issue if Update Available
        if: steps.check.outputs.current != steps.check.outputs.latest
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Pulumi Terraform Bridge Available: ${{ steps.check.outputs.latest }}',
              body: `A new version of pulumi-terraform-bridge is available!
              
              **Current Version:** ${{ steps.check.outputs.current }}
              **Latest Version:** ${{ steps.check.outputs.latest }}
              
              To update, see the [upgrade guide](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/CHANGELOG.md).`,
              labels: ['dependencies', 'pulumi-bridge']
            })
