// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get information about a Yandex Compute Disk Placement group. For more information, see [the official documentation](https://yandex.cloud/docs/compute/concepts/disk#nr-disks).
 *
 * > One of `groupId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh-io/pulumi-yandex";
 *
 * const myGroup = yandex.getComputeDiskPlacementGroup({
 *     groupId: "some_group_id",
 * });
 * export const placementGroupName = myGroup.then(myGroup => myGroup.name);
 * ```
 */
export function getComputeDiskPlacementGroup(args?: GetComputeDiskPlacementGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetComputeDiskPlacementGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getComputeDiskPlacementGroup:getComputeDiskPlacementGroup", {
        "description": args.description,
        "folderId": args.folderId,
        "groupId": args.groupId,
        "labels": args.labels,
        "name": args.name,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputeDiskPlacementGroup.
 */
export interface GetComputeDiskPlacementGroupArgs {
    /**
     * The resource description.
     */
    description?: string;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: string;
    /**
     * The ID of a specific group.
     */
    groupId?: string;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    labels?: {[key: string]: string};
    /**
     * The resource name.
     */
    name?: string;
    /**
     * The [availability zone](https://yandex.cloud/docs/overview/concepts/geo-scope) where resource is located. If it is not provided, the default provider zone will be used.
     */
    zone?: string;
}

/**
 * A collection of values returned by getComputeDiskPlacementGroup.
 */
export interface GetComputeDiskPlacementGroupResult {
    /**
     * The creation timestamp of the resource.
     */
    readonly createdAt: string;
    /**
     * The resource description.
     */
    readonly description?: string;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    readonly folderId: string;
    /**
     * The ID of a specific group.
     */
    readonly groupId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    readonly labels?: {[key: string]: string};
    /**
     * The resource name.
     */
    readonly name?: string;
    /**
     * Status of the Disk Placement Group.
     */
    readonly status: string;
    /**
     * The [availability zone](https://yandex.cloud/docs/overview/concepts/geo-scope) where resource is located. If it is not provided, the default provider zone will be used.
     */
    readonly zone?: string;
}
/**
 * Get information about a Yandex Compute Disk Placement group. For more information, see [the official documentation](https://yandex.cloud/docs/compute/concepts/disk#nr-disks).
 *
 * > One of `groupId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh-io/pulumi-yandex";
 *
 * const myGroup = yandex.getComputeDiskPlacementGroup({
 *     groupId: "some_group_id",
 * });
 * export const placementGroupName = myGroup.then(myGroup => myGroup.name);
 * ```
 */
export function getComputeDiskPlacementGroupOutput(args?: GetComputeDiskPlacementGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetComputeDiskPlacementGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("yandex:index/getComputeDiskPlacementGroup:getComputeDiskPlacementGroup", {
        "description": args.description,
        "folderId": args.folderId,
        "groupId": args.groupId,
        "labels": args.labels,
        "name": args.name,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputeDiskPlacementGroup.
 */
export interface GetComputeDiskPlacementGroupOutputArgs {
    /**
     * The resource description.
     */
    description?: pulumi.Input<string>;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: pulumi.Input<string>;
    /**
     * The ID of a specific group.
     */
    groupId?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The [availability zone](https://yandex.cloud/docs/overview/concepts/geo-scope) where resource is located. If it is not provided, the default provider zone will be used.
     */
    zone?: pulumi.Input<string>;
}
