// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get information about a Yandex CDN Origin Group. For more information, see [the official documentation](https://yandex.cloud/docs/cdn/concepts/origins).
 *
 * > One of `originGroupId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh/pulumi-yandex";
 *
 * const myGroup = yandex.getCdnOriginGroup({
 *     originGroupId: "some_instance_id",
 * });
 * export const originGroupName = myGroup.then(myGroup => myGroup.name);
 * ```
 */
export function getCdnOriginGroup(args?: GetCdnOriginGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetCdnOriginGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getCdnOriginGroup:getCdnOriginGroup", {
        "folderId": args.folderId,
        "name": args.name,
        "originGroupId": args.originGroupId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCdnOriginGroup.
 */
export interface GetCdnOriginGroupArgs {
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: string;
    /**
     * The resource name.
     */
    name?: string;
    /**
     * The ID of a specific origin group.
     */
    originGroupId?: number;
}

/**
 * A collection of values returned by getCdnOriginGroup.
 */
export interface GetCdnOriginGroupResult {
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    readonly folderId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The resource name.
     */
    readonly name: string;
    /**
     * The ID of a specific origin group.
     */
    readonly originGroupId: number;
    readonly origins: outputs.GetCdnOriginGroupOrigin[];
    /**
     * If the option is active (has true value), in case the origin responds with 4XX or 5XX codes, use the next origin from the list.
     */
    readonly useNext: boolean;
}
/**
 * Get information about a Yandex CDN Origin Group. For more information, see [the official documentation](https://yandex.cloud/docs/cdn/concepts/origins).
 *
 * > One of `originGroupId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh/pulumi-yandex";
 *
 * const myGroup = yandex.getCdnOriginGroup({
 *     originGroupId: "some_instance_id",
 * });
 * export const originGroupName = myGroup.then(myGroup => myGroup.name);
 * ```
 */
export function getCdnOriginGroupOutput(args?: GetCdnOriginGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCdnOriginGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("yandex:index/getCdnOriginGroup:getCdnOriginGroup", {
        "folderId": args.folderId,
        "name": args.name,
        "originGroupId": args.originGroupId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCdnOriginGroup.
 */
export interface GetCdnOriginGroupOutputArgs {
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: pulumi.Input<string>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of a specific origin group.
     */
    originGroupId?: pulumi.Input<number>;
}
