// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get information about a Yandex Compute Placement group. For more information, see [the official documentation](https://yandex.cloud/docs/compute/concepts/placement-groups).
 *
 * > One of `groupId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh-io/pulumi-yandex";
 *
 * const myGroup = yandex.getComputePlacementGroup({
 *     groupId: "some_group_id",
 * });
 * export const placementGroupName = myGroup.then(myGroup => myGroup.name);
 * ```
 */
export function getComputePlacementGroup(args?: GetComputePlacementGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetComputePlacementGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getComputePlacementGroup:getComputePlacementGroup", {
        "description": args.description,
        "folderId": args.folderId,
        "groupId": args.groupId,
        "labels": args.labels,
        "name": args.name,
        "placementStrategy": args.placementStrategy,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputePlacementGroup.
 */
export interface GetComputePlacementGroupArgs {
    /**
     * The resource description.
     */
    description?: string;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: string;
    /**
     * The ID of a specific group.
     */
    groupId?: string;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    labels?: {[key: string]: string};
    /**
     * The resource name.
     */
    name?: string;
    /**
     * Placement strategy set for group.
     */
    placementStrategy?: {[key: string]: string};
}

/**
 * A collection of values returned by getComputePlacementGroup.
 */
export interface GetComputePlacementGroupResult {
    /**
     * The creation timestamp of the resource.
     */
    readonly createdAt: string;
    /**
     * The resource description.
     */
    readonly description?: string;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    readonly folderId: string;
    /**
     * The ID of a specific group.
     */
    readonly groupId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    readonly labels?: {[key: string]: string};
    /**
     * The resource name.
     */
    readonly name?: string;
    /**
     * Placement strategy set for group.
     */
    readonly placementStrategy?: {[key: string]: string};
}
/**
 * Get information about a Yandex Compute Placement group. For more information, see [the official documentation](https://yandex.cloud/docs/compute/concepts/placement-groups).
 *
 * > One of `groupId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh-io/pulumi-yandex";
 *
 * const myGroup = yandex.getComputePlacementGroup({
 *     groupId: "some_group_id",
 * });
 * export const placementGroupName = myGroup.then(myGroup => myGroup.name);
 * ```
 */
export function getComputePlacementGroupOutput(args?: GetComputePlacementGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetComputePlacementGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("yandex:index/getComputePlacementGroup:getComputePlacementGroup", {
        "description": args.description,
        "folderId": args.folderId,
        "groupId": args.groupId,
        "labels": args.labels,
        "name": args.name,
        "placementStrategy": args.placementStrategy,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputePlacementGroup.
 */
export interface GetComputePlacementGroupOutputArgs {
    /**
     * The resource description.
     */
    description?: pulumi.Input<string>;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: pulumi.Input<string>;
    /**
     * The ID of a specific group.
     */
    groupId?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * Placement strategy set for group.
     */
    placementStrategy?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
