// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get information about Serverless Event Router Bus.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * ```
 */
export function getServerlessEventrouterBus(args?: GetServerlessEventrouterBusArgs, opts?: pulumi.InvokeOptions): Promise<GetServerlessEventrouterBusResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getServerlessEventrouterBus:getServerlessEventrouterBus", {
        "busId": args.busId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getServerlessEventrouterBus.
 */
export interface GetServerlessEventrouterBusArgs {
    /**
     * ID of the bus
     */
    busId?: string;
    /**
     * Name of the bus
     */
    name?: string;
}

/**
 * A collection of values returned by getServerlessEventrouterBus.
 */
export interface GetServerlessEventrouterBusResult {
    /**
     * ID of the bus
     */
    readonly busId?: string;
    /**
     * ID of the cloud that the bus resides in
     */
    readonly cloudId: string;
    /**
     * Creation timestamp
     */
    readonly createdAt: string;
    /**
     * Deletion protection
     */
    readonly deletionProtection: boolean;
    /**
     * Description of the bus
     */
    readonly description: string;
    /**
     * ID of the folder that the bus belongs to
     */
    readonly folderId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Bus labels
     */
    readonly labels: {[key: string]: string};
    /**
     * Name of the bus
     */
    readonly name?: string;
}
/**
 * Get information about Serverless Event Router Bus.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * ```
 */
export function getServerlessEventrouterBusOutput(args?: GetServerlessEventrouterBusOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerlessEventrouterBusResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("yandex:index/getServerlessEventrouterBus:getServerlessEventrouterBus", {
        "busId": args.busId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getServerlessEventrouterBus.
 */
export interface GetServerlessEventrouterBusOutputArgs {
    /**
     * ID of the bus
     */
    busId?: pulumi.Input<string>;
    /**
     * Name of the bus
     */
    name?: pulumi.Input<string>;
}
