// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get information about a Yandex VPC address. For more information, see [the official documentation](https://yandex.cloud/docs/vpc/concepts/address).
 *
 * This data source is used to define [VPC Address](https://yandex.cloud/docs/vpc/concepts/address) that can be used by other resources.
 *
 * > One of `addressId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh-io/pulumi-yandex";
 *
 * const addr = yandex.getVpcAddress({
 *     addressId: "my-address-id",
 * });
 * ```
 */
export function getVpcAddress(args?: GetVpcAddressArgs, opts?: pulumi.InvokeOptions): Promise<GetVpcAddressResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getVpcAddress:getVpcAddress", {
        "addressId": args.addressId,
        "folderId": args.folderId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcAddress.
 */
export interface GetVpcAddressArgs {
    /**
     * ID of the address.
     */
    addressId?: string;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: string;
    /**
     * The resource name.
     */
    name?: string;
}

/**
 * A collection of values returned by getVpcAddress.
 */
export interface GetVpcAddressResult {
    /**
     * ID of the address.
     */
    readonly addressId: string;
    /**
     * The creation timestamp of the resource.
     */
    readonly createdAt: string;
    /**
     * The `true` value means that resource is protected from accidental deletion.
     */
    readonly deletionProtection: boolean;
    /**
     * The resource description.
     */
    readonly description: string;
    readonly dnsRecords: outputs.GetVpcAddressDnsRecord[];
    readonly externalIpv4Addresses: outputs.GetVpcAddressExternalIpv4Address[];
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    readonly folderId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    readonly labels: {[key: string]: string};
    /**
     * The resource name.
     */
    readonly name: string;
    /**
     * `false` means that address is ephemeral.
     */
    readonly reserved: boolean;
    /**
     * `true` if address is used.
     */
    readonly used: boolean;
}
/**
 * Get information about a Yandex VPC address. For more information, see [the official documentation](https://yandex.cloud/docs/vpc/concepts/address).
 *
 * This data source is used to define [VPC Address](https://yandex.cloud/docs/vpc/concepts/address) that can be used by other resources.
 *
 * > One of `addressId` or `name` should be specified.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh-io/pulumi-yandex";
 *
 * const addr = yandex.getVpcAddress({
 *     addressId: "my-address-id",
 * });
 * ```
 */
export function getVpcAddressOutput(args?: GetVpcAddressOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVpcAddressResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("yandex:index/getVpcAddress:getVpcAddress", {
        "addressId": args.addressId,
        "folderId": args.folderId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcAddress.
 */
export interface GetVpcAddressOutputArgs {
    /**
     * ID of the address.
     */
    addressId?: pulumi.Input<string>;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: pulumi.Input<string>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
}
