// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creates a Yandex KMS asymmetric signature key that can be used for cryptographic operation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@airoh/pulumi-yandex";
 *
 * //
 * // Create a new KMS Assymetric Signature Key.
 * //
 * const key_a = new yandex.KmsAsymmetricSignatureKey("key-a", {
 *     description: "description for key",
 *     signatureAlgorithm: "RSA_2048_SIGN_PSS_SHA_256",
 * });
 * ```
 *
 * ## Import
 *
 * The resource can be imported by using their `resource ID`. For getting the resource ID you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or [YC CLI](https://yandex.cloud/docs/cli/quickstart).
 *
 * ```sh
 * $ pulumi import yandex:index/kmsAsymmetricSignatureKey:KmsAsymmetricSignatureKey <resource Name> <resource Id>
 * ```
 *
 * ```sh
 * $ pulumi import yandex:index/kmsAsymmetricSignatureKey:KmsAsymmetricSignatureKey key-a abjjf**********p3gp8
 * ```
 */
export class KmsAsymmetricSignatureKey extends pulumi.CustomResource {
    /**
     * Get an existing KmsAsymmetricSignatureKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KmsAsymmetricSignatureKeyState, opts?: pulumi.CustomResourceOptions): KmsAsymmetricSignatureKey {
        return new KmsAsymmetricSignatureKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/kmsAsymmetricSignatureKey:KmsAsymmetricSignatureKey';

    /**
     * Returns true if the given object is an instance of KmsAsymmetricSignatureKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KmsAsymmetricSignatureKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KmsAsymmetricSignatureKey.__pulumiType;
    }

    /**
     * The creation timestamp of the resource.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The `true` value means that resource is protected from accidental deletion.
     */
    declare public readonly deletionProtection: pulumi.Output<boolean | undefined>;
    /**
     * The resource description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    declare public readonly folderId: pulumi.Output<string>;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The resource name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Signature algorithm to be used with a new key. The default value is `RSA_2048_SIGN_PSS_SHA_256`.
     */
    declare public readonly signatureAlgorithm: pulumi.Output<string | undefined>;
    /**
     * The status of the key.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a KmsAsymmetricSignatureKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KmsAsymmetricSignatureKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KmsAsymmetricSignatureKeyArgs | KmsAsymmetricSignatureKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KmsAsymmetricSignatureKeyState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["deletionProtection"] = state?.deletionProtection;
            resourceInputs["description"] = state?.description;
            resourceInputs["folderId"] = state?.folderId;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["signatureAlgorithm"] = state?.signatureAlgorithm;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as KmsAsymmetricSignatureKeyArgs | undefined;
            resourceInputs["deletionProtection"] = args?.deletionProtection;
            resourceInputs["description"] = args?.description;
            resourceInputs["folderId"] = args?.folderId;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["signatureAlgorithm"] = args?.signatureAlgorithm;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KmsAsymmetricSignatureKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering KmsAsymmetricSignatureKey resources.
 */
export interface KmsAsymmetricSignatureKeyState {
    /**
     * The creation timestamp of the resource.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The `true` value means that resource is protected from accidental deletion.
     */
    deletionProtection?: pulumi.Input<boolean>;
    /**
     * The resource description.
     */
    description?: pulumi.Input<string>;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * Signature algorithm to be used with a new key. The default value is `RSA_2048_SIGN_PSS_SHA_256`.
     */
    signatureAlgorithm?: pulumi.Input<string>;
    /**
     * The status of the key.
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a KmsAsymmetricSignatureKey resource.
 */
export interface KmsAsymmetricSignatureKeyArgs {
    /**
     * The `true` value means that resource is protected from accidental deletion.
     */
    deletionProtection?: pulumi.Input<boolean>;
    /**
     * The resource description.
     */
    description?: pulumi.Input<string>;
    /**
     * The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
     */
    folderId?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs which assigned to resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * Signature algorithm to be used with a new key. The default value is `RSA_2048_SIGN_PSS_SHA_256`.
     */
    signatureAlgorithm?: pulumi.Input<string>;
}
